const field=(key,label,aliases=[],normalization='')=>({key,label,aliases:[label,...aliases].map(s=>s.toLowerCase()),normalization});
export const TEMPLATES={
 general:{label:'범용 연구',description:'분야에 관계없이 대상·방법·조건·근거를 비교합니다.',fields:[field('target','연구 대상',['대상','target']),field('method','방법·접근',['방법','method']),field('parameters','핵심 조건',['조건','parameters']),field('time','기간·시점',['기간','시점','time'],'duration'),field('metric','측정·평가 기준',['평가 기준','지표','metric']),field('baseline','비교 기준',['비교군','baseline']),field('sample','자료·표본 규모',['자료 규모','표본','sample'])]},
 biology:{label:'생명과학·실험 연구',description:'모델·물질·처리 조건·대조군을 비교합니다.',fields:[field('cell','세포 / 모델',['세포','세포주','모델','cell','cell line','model']),field('compound','물질',['약물','후보 물질','compound','drug']),field('concentration','처리 농도',['농도','concentration','dose'],'concentration'),field('duration','처리 시간',['시간','duration','treatment time','time'],'duration'),field('assay','측정 방법',['측정','분석 방법','assay','readout']),field('control','대조군',['control','controls']),field('replicates','반복 측정',['반복','반복수','replicates','replicate'])]},
 computational:{label:'계산·AI·데이터 연구',description:'데이터·방법·설정·검증 방식을 비교합니다.',fields:[field('dataset','데이터셋',['데이터','dataset']),field('method','모델·알고리즘',['모델','알고리즘','방법','model','method']),field('parameters','설정·하이퍼파라미터',['설정','parameters','hyperparameters']),field('split','학습·평가 분할',['분할','split']),field('metric','평가지표',['지표','metric']),field('baseline','비교 방법',['비교 기준','baseline']),field('replicates','반복·시드',['시드','반복','seeds'])]},
 quantitative:{label:'설문·관찰·정량 연구',description:'모집단·표본·변수·분석 기준을 비교합니다.',fields:[field('population','대상·모집단',['대상','모집단','population']),field('sampling','표본·모집 방법',['표본','모집','sampling']),field('variables','변수·측정 도구',['변수','측정 도구','variables']),field('time','조사 기간',['기간','time']),field('analysis','분석 방법',['방법','analysis']),field('confounders','비교군·교란요인',['비교군','교란요인','confounders']),field('size','표본 수',['대상자 수','표본수','n'])]},
 qualitative:{label:'인터뷰·현장·질적 연구',description:'참여자·수집 맥락·코딩·해석 기준을 비교합니다.',fields:[field('participants','참여자·사례',['참여자','사례','participants']),field('collection','자료 수집 방법',['수집 방법','인터뷰 방식','collection']),field('context','수집 맥락',['맥락','context']),field('time','수집 기간',['기간','time']),field('analysis','분석·코딩 방법',['분석 방법','코딩','analysis']),field('reflexivity','검토·성찰 기준',['검토 기준','성찰','reflexivity']),field('scope','자료 범위',['범위','scope'])]},
 theoretical:{label:'문헌·인문·이론 연구',description:'연구 질문·대상 문헌·가정·논증 근거를 비교합니다.',fields:[field('question','연구 질문',['질문','question']),field('corpus','대상 문헌·자료',['대상 문헌','대상 자료','corpus']),field('framework','이론·분석 틀',['이론','분석 틀','framework']),field('scope','시기·범위',['범위','시기','scope']),field('method','해석·논증 방법',['방법','method']),field('assumptions','가정·반론',['가정','반론','assumptions']),field('evidence','근거·한계',['근거','한계','evidence'])]},
 custom:{label:'직접 정의',description:'연구에 필요한 비교 항목을 직접 정합니다.',fields:[]}
};
export function fieldsFor(item){return item?.conditionFields?.length?item.conditionFields:TEMPLATES.biology.fields;}
export function templateFields(id='general',labels=[]){
 if(id==='custom'){if(!Array.isArray(labels)||labels.length<2||labels.length>12||labels.some(l=>typeof l!=='string'||!l.trim()||l.length>50)||new Set(labels.map(l=>l.trim())).size!==labels.length)throw new Error('서로 다른 비교 항목을 2~12개 입력하세요.');return labels.map((label,i)=>field('field_'+(i+1),label.trim()));}
 if(!Object.hasOwn(TEMPLATES,id))throw new Error('연구 유형을 확인하세요.');return structuredClone(TEMPLATES[id].fields);
}
