import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.FLYLABS_QA_URL||'http://127.0.0.1:4220',label=base.startsWith('https:')?'public':'local';
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();
page.setDefaultTimeout(10000);const checks=[],errors=[],unexpectedRequests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET'||new URL(r.url()).origin!==new URL(base).origin)unexpectedRequests.push(r.method()+' '+r.url());});
const nav=async name=>{await page.getByRole('navigation',{name:'주 메뉴'}).getByRole('button',{name,exact:true}).click();};
const step=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
await mkdir('docs',{recursive:true});
try{
 await step('public onboarding and synthetic examples across four research types',async()=>{await page.goto(base);await expect(page.getByRole('heading',{level:1,name:'처리 시간이 달라요'})).toBeVisible();await expect(page.getByText('이 브라우저에 저장 · 외부 AI 미연결',{exact:true})).toBeVisible();await expect(page.getByLabel('자료 프로젝트').locator('option')).toHaveCount(4);await page.screenshot({path:`docs/qa-demo-${label}-desktop.png`,fullPage:true,animations:'disabled'});});
 await step('dashboard leads with differences and presentation mode walks the flow',async()=>{await expect(page.locator('.th-figure .th-fig')).toHaveCount(2);await expect(page.locator('.th-figure')).toContainText('24 h');await expect(page.locator('.th-figure')).toContainText('48 h');await expect(page.locator('.th-cta')).toHaveText('두 기록 나란히 보기');await page.getByRole('button',{name:'시연 모드',exact:true}).click();const guide=page.getByRole('region',{name:'시연 가이드'});await expect(guide).toContainText('첫 화면');await page.keyboard.press('ArrowRight');await expect(page.getByRole('navigation',{name:'주 메뉴'}).getByRole('button',{name:'자료 라이브러리',exact:true})).toHaveAttribute('aria-current','page');await page.keyboard.press('Escape');await expect(guide).toHaveCount(0);await nav('연구 워크스페이스');});
 await step('source comparison, missing values, real execution trace',async()=>{await nav('조건 비교');await expect(page.locator('.condition-table tbody tr')).toHaveCount(7);await page.getByRole('button',{name:'비교 실행·기록',exact:true}).click();await expect(page.getByText('외부 AI 판단 없이 규칙으로 실행한 기록입니다.',{exact:true})).toBeVisible();await page.locator('.evidence-value').first().click();await expect(page.locator('.source-line.focused')).toHaveCount(1);await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();});
 await step('computational research compares data splits and preserves missing seed',async()=>{await page.getByLabel('자료 프로젝트').selectOption({label:'문서 분류 방법 비교 · 예시'});await expect(page.locator('.condition-table')).toContainText('학습 80%');await expect(page.locator('.condition-table')).toContainText('학습 70%');await expect(page.locator('.condition-table')).toContainText('확인 필요');});
 await step('preparation preserves source and starts notebook',async()=>{await nav('연구 준비표');await page.getByLabel('준비표 연구자 메모').fill('평가 데이터 분할을 먼저 맞춘다.');await page.getByRole('button',{name:'저장 후 랩노트 시작',exact:true}).click();await expect(page.getByRole('button',{name:'노트 작성',exact:true})).toBeVisible();await expect(page.locator('.notebook-fields')).toContainText('평가 데이터 분할을 먼저 맞춘다.');});
 await step('notebook edit persists across reload with revision history',async()=>{await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.getByLabel('연구 목적',{exact:true}).fill('공개 체험판 저장 검증 · 동일 평가셋 비교');await page.getByRole('button',{name:'노트 저장',exact:true}).click();await expect(page.getByRole('button',{name:'노트 작성',exact:true})).toBeVisible();await page.reload();await expect(page.locator('.notebook-fields')).toContainText('공개 체험판 저장 검증 · 동일 평가셋 비교');await page.getByRole('button',{name:'수정 이력',exact:true}).click();await expect(page.locator('.history-row')).toHaveCount(1);});
 await step('attachment upload and download preserve binary bytes',async()=>{await page.getByRole('button',{name:'준비·파일 관리'}).click();const raw=Buffer.from([0,1,2,3,10,128,255]);await page.locator('.upload-zone input[type=file]').setInputFiles({name:'qa-result.bin',mimeType:'application/octet-stream',buffer:raw});const link=page.getByRole('link',{name:/qa-result.bin/});await expect(link).toBeVisible();const event=page.waitForEvent('download');await link.click();const file=await event;assert.deepEqual(await readFile(await file.path()),raw);});
 await step('full local backup includes evidence, revisions and raw attachment',async()=>{await page.getByRole('button',{name:'연구실 설정',exact:true}).click();const event=page.waitForEvent('download');await page.getByRole('button',{name:'전체 기록 백업',exact:true}).click();const file=await event,data=JSON.parse(await readFile(await file.path(),'utf8'));assert.equal(data.schema,'flylabs-browser-demo-v1');const w=data.state.workspaces[0];assert.ok(w.evidence.preparations.length);assert.equal(w.files.find(f=>f.name==='qa-result.bin').data,Buffer.from([0,1,2,3,10,128,255]).toString('base64'));});
 await step('source editing keeps original revision',async()=>{await nav('자료 라이브러리');await page.locator('.source-title').first().click();await page.getByRole('button',{name:'자료 수정',exact:true}).click();await page.getByLabel('자료 원문',{exact:true}).fill('데이터셋: 합성 검증 데이터\n모델: QA\n분할: 80/20');await page.getByRole('button',{name:'자료 저장',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.source-title').first().click();await expect(page.locator('.source-details')).toContainText('보존된 자료 수정 기록 1개');await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();});
 await step('all routes render at mobile width without overflow',async()=>{await page.setViewportSize({width:390,height:844});for(const name of ['연구 워크스페이스','조건 비교','연구 준비표','랩노트','오늘의 연구실','실험 관리','진행 기록','자원 · 장비 예약','인수인계','판단 · 처리 기록']){await page.getByRole('button',{name:'메뉴 열기'}).click();await nav(name);await expect(page.getByRole('navigation',{name:'주 메뉴'}).getByRole('button',{name,exact:true})).toHaveAttribute('aria-current','page');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+name);}await page.getByRole('button',{name:'메뉴 열기'}).click();await nav('연구 워크스페이스');await page.screenshot({path:`docs/qa-demo-${label}-mobile.png`,fullPage:true,animations:'disabled'});});
 await step('no external requests, no data POSTs, no runtime errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(unexpectedRequests,[]);});
}catch(e){errors.push(e.stack);await page.screenshot({path:`docs/qa-demo-${label}-failure.png`,fullPage:true,animations:'disabled'});console.error(e);process.exitCode=1;}
finally{await writeFile(`docs/qa-demo-${label}.json`,JSON.stringify({version:'5.2.0',url:base,at:new Date().toISOString(),checks,errors,unexpectedRequests},null,2));await browser.close();}
