import {chromium,expect} from '@playwright/test';
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {createApp} from '../server/index.mjs';
process.env.GEMINI_API_KEY='synthetic-qa-key';process.env.JEV_API_KEY='synthetic-qa-key';
const fakeAssistant=async(url,opt)=>{const prompt=JSON.parse(opt.body).contents[0].parts[0].text,results=prompt.includes('Task: results.');return {ok:true,json:async()=>({modelVersion:'simulated-browser-qa',candidates:[{content:{parts:[{text:JSON.stringify({fields:results?{observations:'방법 A: 12개. 방법 B: 13개.',analysis:'유의성 검정 미수행',conclusion:'추가 확인 필요'}:{objective:'두 분석 방법의 결과 비교',design:'같은 이미지의 두 방법 비교'},missing:['대조 기준 확인 필요'],citations:['input']})}]}}]})};};
const fakeJev=async()=>({ok:true,json:async()=>({answers:{category:{choice:'material_wait',confidence:.95},status:{choice:'blocked',confidence:.94}}})});
const dir=await mkdtemp(path.join(os.tmpdir(),'flylabs-browser-v2-')),app=createApp({dataDir:dir,assistantOptions:{apiKey:'synthetic',fetch:fakeAssistant},jevOptions:{apiKey:'synthetic',fetch:fakeJev}});
await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
const browser=await chromium.launch(),context=await browser.newContext({baseURL:base,viewport:{width:1440,height:1050}}),page=await context.newPage();page.setDefaultTimeout(12000);
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('docs',{recursive:true});
const password='Browser-QA-passphrase-2026!';
async function step(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function nav(name,p=page){const b=p.getByRole('navigation',{name:'주 메뉴'}).getByRole('button',{name,exact:true});await b.click();await expect(b).toHaveAttribute('aria-current','page');}
const modal=()=>page.getByRole('dialog');
async function register(p,email,name){await p.getByRole('button',{name:'회원가입',exact:true}).click();await p.getByLabel('이름',{exact:true}).fill(name);await p.getByLabel('이메일',{exact:true}).fill(email);await p.getByLabel('비밀번호',{exact:true}).fill(password);await p.getByRole('button',{name:'계정 만들기',exact:true}).click();await expect(p.getByRole('navigation',{name:'주 메뉴'})).toBeVisible();}
let wid,eid,invitation,editorContext,editorPage;
try{
 await step('authentication gate and first account onboarding',async()=>{await page.goto(base);await expect(page.getByRole('heading',{name:'연구를 이어갈 시간입니다.'})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/qa-auth.png',fullPage:true,animations:'disabled'});await register(page,'owner@example.test','연구 관리자');const options=await page.getByLabel('연구실 선택').locator('option').evaluateAll(xs=>xs.map(x=>({id:x.value,name:x.textContent})));wid=options.find(x=>x.name==='연구 관리자의 연구실').id;await page.getByLabel('연구실 선택').selectOption(wid);await expect(page.locator('.demo-notice')).toHaveCount(0);});
 await step('create an experiment notebook',async()=>{await nav('랩노트');await page.getByRole('button',{name:'새 실험·노트',exact:true}).click();await modal().getByLabel('실험명',{exact:true}).fill('이미지 분석 방법 비교');await modal().getByLabel('프로젝트',{exact:true}).fill('Reproducibility');await modal().getByLabel('준비 항목',{exact:true}).fill('원본 이미지 확인');await modal().getByRole('button',{name:'실험 등록',exact:true}).click();await expect(page.getByRole('heading',{name:'이미지 분석 방법 비교',exact:true})).toBeVisible();eid=new URL(page.url()).hash.split('/')[1];});
 await step('write experiment plans and results in separate fields',async()=>{await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.getByLabel('연구 목적',{exact:true}).fill('두 이미지 분석 방법의 일치도 확인');await page.getByLabel('가설 / 연구 질문',{exact:true}).fill('방법 간 차이가 있는가?');await page.getByLabel('실험 설계',{exact:true}).fill('동일 이미지 12장을 두 방법으로 비교');await page.getByLabel('시료·재료·조건',{exact:true}).fill('기존 이미지 IMG-001~012');await page.getByLabel('실행 절차',{exact:true}).fill('연구자가 제공한 분석 절차 v1');await page.getByRole('button',{name:'결과·해석',exact:true}).click();await page.getByLabel('관찰 결과',{exact:true}).fill('방법 A 12개, 방법 B 13개');await page.getByLabel('분석·해석',{exact:true}).fill('통계적 검정은 수행하지 않음');await page.getByLabel('결론',{exact:true}).fill('현재 데이터로 차이를 확정할 수 없음');await page.getByLabel('수정 이유',{exact:true}).fill('첫 계획과 관찰 기록');await page.locator('.notebook-save').getByRole('button',{name:'노트 저장',exact:true}).click();await expect(page.getByRole('button',{name:'노트 작성',exact:true})).toBeVisible();await expect(page.getByText('방법 A 12개, 방법 B 13개',{exact:true})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/qa-notebook-results.png',fullPage:true,animations:'disabled'});});
 await step('recover an unsaved tab draft after navigation',async()=>{await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.getByLabel('관찰 결과',{exact:true}).fill('임시 작성: 방법 A 12개, 방법 B 13개');await nav('오늘의 연구실');await page.goto(base+'/#notebook/'+eid);await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.getByRole('button',{name:'결과·해석',exact:true}).click();await expect(page.getByLabel('관찰 결과',{exact:true})).toHaveValue('임시 작성: 방법 A 12개, 방법 B 13개');await page.getByRole('button',{name:'편집 취소',exact:true}).click();});
 await step('execution notes and append-only corrections',async()=>{await page.getByRole('button',{name:/^실행 기록 \d/}).click();await page.getByLabel('실행 기록',{exact:true}).fill('IMG-001의 원본 파일을 확인했습니다.');await page.getByRole('button',{name:'실행 기록 저장',exact:true}).click();await expect(page.getByText('IMG-001의 원본 파일을 확인했습니다.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'정정 기록 추가',exact:true}).click();await page.getByLabel('정정 내용',{exact:true}).fill('정정: IMG-002 파일을 확인했습니다.');await page.getByRole('button',{name:'실행 기록 저장',exact:true}).click();await expect(page.locator('.entry-feed article')).toHaveCount(2);});
 await step('AI produces a reviewable draft and applies only selected fields',async()=>{await page.getByRole('button',{name:/^AI 도우미/}).click();await page.getByLabel('AI 작업',{exact:true}).selectOption('plan');await page.getByLabel('정리할 원문',{exact:true}).fill('두 분석 방법을 같은 이미지로 비교하고자 합니다.');await page.getByRole('button',{name:'선택한 내용으로 초안 생성',exact:true}).click();await expect(page.locator('.ai-draft')).toHaveCount(1);await page.locator('.ai-draft').getByRole('checkbox',{name:'실험 설계',exact:true}).uncheck();await page.getByRole('button',{name:'선택 항목 반영',exact:true}).click();await expect(page.getByText(/검토 후 반영된 초안/)).toBeVisible();await page.getByRole('button',{name:'실험 계획',exact:true}).click();await expect(page.getByText('두 분석 방법의 결과 비교',{exact:true})).toBeVisible();await expect(page.getByText('동일 이미지 12장을 두 방법으로 비교',{exact:true})).toBeVisible();});
 await step('uploaded raw files preserve bytes and Jev status needs approval',async()=>{await page.getByRole('button',{name:'준비·파일 관리'}).click();await page.locator('.upload-zone input[type=file]').setInputFiles({name:'raw-results.csv',mimeType:'text/csv',buffer:Buffer.from('method,value\nA,12\nB,13\n')});const link=page.getByRole('link',{name:/raw-results.csv/});await expect(link).toBeVisible();assert.equal(await (await page.request.get(await link.getAttribute('href'))).text(),'method,value\nA,12\nB,13\n');await page.getByRole('button',{name:'진행 기록',exact:true}).last().click();await modal().getByLabel('진행 메모',{exact:true}).fill('시약 부족으로 실험을 보류했습니다.');await modal().getByRole('radio',{name:/Jev로 판단/}).check();await modal().getByRole('button',{name:'기록 저장'}).click();await expect(page.getByLabel('진행 상태 변경')).toHaveValue('planned');await page.locator('.proposal').getByRole('button',{name:'반영',exact:true}).click();await expect(page.getByLabel('진행 상태 변경')).toHaveValue('blocked');await page.getByRole('button',{name:'랩노트 열기',exact:true}).click();});
 await step('signing locks the notebook; reopening preserves signed history',async()=>{await page.getByRole('button',{name:'결과·해석',exact:true}).click();await page.getByRole('button',{name:'검토 후 서명',exact:true}).click();await modal().getByRole('button',{name:'확인하고 서명',exact:true}).click();await expect(page.locator('.signed-notice')).toBeVisible();await expect(page.getByRole('button',{name:'노트 작성',exact:true})).toHaveCount(0);await page.reload();await expect(page.locator('.signed-notice')).toBeVisible();await page.getByRole('button',{name:'새 리비전 열기',exact:true}).click();await modal().getByLabel('수정을 재개하는 이유',{exact:true}).fill('후속 관찰 추가');await modal().getByRole('button',{name:'새 리비전 열기',exact:true}).click();await page.getByRole('button',{name:'수정 이력',exact:true}).click();await expect(page.getByText(/서명 기록/)).toBeVisible();await page.locator('.history-row').first().click();await expect(modal().getByText('방법 A 12개, 방법 B 13개',{exact:true})).toBeVisible();await modal().getByRole('button',{name:'닫기',exact:true}).click();});
 await step('export notebook with source values',async()=>{const promise=page.waitForEvent('download');await page.getByRole('button',{name:'노트 내보내기',exact:true}).click();const d=await promise;assert.match(d.suggestedFilename(),/^FL-001-notebook-r\d+\.md$/);});
 await step('create email-bound editor invitation',async()=>{await page.getByRole('button',{name:'연구실 설정',exact:true}).click();await page.getByLabel('초대할 이메일',{exact:true}).fill('editor@example.test');await page.getByRole('button',{name:'초대 링크 만들기',exact:true}).click();invitation=await page.getByLabel('생성된 초대 링크',{exact:true}).inputValue();assert.ok(invitation.includes('#invite/'));});
 await step('second account joins shared lab and sees notebook',async()=>{editorContext=await browser.newContext({baseURL:base,viewport:{width:1280,height:900}});editorPage=await editorContext.newPage();editorPage.setDefaultTimeout(12000);editorPage.on('pageerror',e=>errors.push(e.message));await editorPage.goto(invitation);await register(editorPage,'editor@example.test','공동 연구원');await expect(editorPage.getByLabel('연구실 선택')).toHaveValue(wid);await nav('랩노트',editorPage);await editorPage.getByRole('button',{name:/이미지 분석 방법 비교/}).click();await expect(editorPage.getByText('두 분석 방법의 결과 비교',{exact:true})).toBeVisible();});
 await step('concurrent edits reject stale overwrites and preserve unsaved text',async()=>{await editorPage.getByRole('button',{name:'노트 작성',exact:true}).click();await editorPage.getByLabel('연구 목적',{exact:true}).fill('공동 연구원의 미저장 편집');await page.goto(base+'/#notebook/'+eid);await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.getByLabel('연구 목적',{exact:true}).fill('관리자가 먼저 저장한 목적');await page.locator('.notebook-save').getByRole('button',{name:'노트 저장',exact:true}).click();await editorPage.locator('.notebook-save').getByRole('button',{name:'노트 저장',exact:true}).click();await expect(editorPage.getByRole('alert')).toContainText('먼저 수정');await expect(editorPage.getByLabel('연구 목적',{exact:true})).toHaveValue('공동 연구원의 미저장 편집');await editorPage.getByRole('button',{name:'편집 취소',exact:true}).click();await editorPage.reload();await expect(editorPage.getByText('관리자가 먼저 저장한 목적',{exact:true})).toBeVisible();});
 await step('viewer role allows reading and rejects direct writes',async()=>{await page.getByRole('button',{name:'연구실 설정',exact:true}).click();await page.getByLabel('공동 연구원 권한',{exact:true}).selectOption('viewer');await expect(page.getByLabel('공동 연구원 권한',{exact:true})).toHaveValue('viewer');await editorPage.reload();await expect(editorPage.locator('.readonly-banner')).toBeVisible();await expect(editorPage.getByRole('button',{name:'노트 작성',exact:true})).toHaveCount(0);const r=await editorPage.request.post('/api/workspaces/'+wid+'/actions',{data:{type:'notebook.save',payload:{experimentId:eid,expectedRevision:0,fields:{objective:'denied'}}}});assert.equal(r.status(),403);});
 await step('handover includes notebook content',async()=>{await nav('인수인계');await page.getByRole('button',{name:'인수인계 초안 만들기'}).click();await expect(page.locator('.draft-text')).toContainText('관리자가 먼저 저장한 목적');await expect(page.locator('.draft-text')).toContainText('raw-results.csv');});
 await step('mobile notebook, editor and team settings fit screen',async()=>{await page.setViewportSize({width:390,height:844});await page.goto(base+'/#notebook/'+eid);await expect(page.getByRole('heading',{name:'이미지 분석 방법 비교',exact:true})).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/qa-mobile-notebook.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'노트 작성',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/qa-mobile-editor.png',fullPage:true,animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'편집 취소',exact:true}).click();await page.getByRole('button',{name:'메뉴 열기'}).click();await page.getByRole('button',{name:'연구실 설정',exact:true}).click();await expect(page.getByRole('heading',{level:1})).toContainText('연구실과 계정');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));});
 await step('logout removes authenticated access',async()=>{await page.getByRole('button',{name:'메뉴 열기'}).click();await page.getByRole('button',{name:'로그아웃',exact:true}).click();await expect(page.getByRole('heading',{name:'연구를 이어갈 시간입니다.'})).toBeVisible();const r=await page.request.get('/api/workspaces');assert.equal(r.status(),401);});
 await step('no browser runtime errors',async()=>assert.deepEqual(errors,[]));
}catch(e){errors.push(e.stack);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/qa-failure.png',fullPage:true,animations:'disabled'});console.error(e);process.exitCode=1;}
finally{await writeFile('docs/qa-report.json',JSON.stringify({version:'4.0.0',generatedAt:new Date().toISOString(),checks,errors,providerMode:'Simulated transport in browser QA; actual Jev and Gemini calls recorded separately in live-ai-check.json.'},null,2));await browser.close();await new Promise(r=>app.server.close(r));app.store.close();await rm(dir,{recursive:true,force:true});}
