import {useEffect,useRef,useState} from 'react';
import {useLab} from './context';
import {Button,Empty,Field,Icon,Modal,SectionHeading} from './components';
import {api,download,stored,storePreference,today} from './lib';
import {extractFields,compareDocuments,createPlan,planMarkdown} from '../shared/research.mjs';
import {TEMPLATES,fieldsFor} from '../shared/templates.mjs';
import type {ConditionField,EvidenceDocument,EvidenceProject,EvidenceValue,Preparation} from './types';

type Graph={nodes:{id:string}[];edges:{source:string;target:string;weight:number}[];dataset:string;[key:string]:unknown};
const kindLabels:Record<string,string>={paper:'논문·초록',note:'실험 기록',meeting:'회의 메모',protocol:'프로토콜'};
const resultLabels:Record<string,string>={same:'조건 일치',different:'조건 차이',missing:'확인 필요',conflict:'원문 내 충돌'};
function Network({graph}:{graph:Graph|null}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(!canvas.current||!graph)return;const c=canvas.current,ctx=c.getContext('2d');if(!ctx)return;const width=640,height=380;c.width=width*2;c.height=height*2;ctx.scale(2,2);ctx.clearRect(0,0,width,height);
  const positions=new Map(graph.nodes.map((n,i)=>{const a=i*Math.PI*(3-Math.sqrt(5)),r=34+Math.sqrt(i)*25;return [String(n.id),{x:width/2+Math.cos(a)*r*1.6,y:height/2+Math.sin(a)*r}];}));
  for(const e of graph.edges){const a=positions.get(String(e.source)),b=positions.get(String(e.target));if(!a||!b)continue;ctx.strokeStyle='rgba(132,207,181,'+Math.min(.5,.09+Math.log(1+e.weight)/25)+')';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
  graph.nodes.forEach((n,i)=>{const p=positions.get(String(n.id))!;ctx.beginPath();ctx.arc(p.x,p.y,i<5?7:3.8,0,Math.PI*2);ctx.fillStyle=i<5?'#efdbb1':'#79b99b';ctx.fill();});
 },[graph]);return <canvas className="connectome-canvas" ref={canvas} role="img" aria-label="MaleCNS의 32개 뉴런·69개 연결 부분집합. 위치는 화면 표시용이며 해부학적 위치가 아닙니다."/>;
}
function SourceDialog({doc,line,onClose,onEdit}:{doc:EvidenceDocument;line:number;onClose:()=>void;onEdit:()=>void}){
 const FIELDS:ConditionField[]=fieldsFor(doc);
 const {post,act,busy,health,canEdit}=useLab();const [keys,setKeys]=useState<Record<string,string[]>>({});
 return <Modal title={doc.title} wide onClose={onClose}><div className="modal-body source-dialog"><div className="source-meta"><span>{kindLabels[doc.kind]||'자료'} · r{doc.version}</span><span>{doc.synthetic?'합성 예시':doc.abstractOnly?'공개 초록':'등록 원문'}</span></div>
 {doc.url&&<a href={doc.url} target="_blank" rel="noreferrer">원문 페이지 열기 ↗</a>}
 <div className="source-lines">{doc.text.split(/\r?\n/).map((t,i)=><div key={i} className={line===i+1?'source-line focused':'source-line'}><span>L{i+1}</span><p>{t||' '}</p></div>)}</div>
 <div className="source-actions"><Button kind="secondary" onClick={()=>download(doc.title+'.txt',doc.text)}>원문 내려받기</Button>{canEdit&&<Button kind="secondary" onClick={onEdit}>자료 수정</Button>}</div>
 <section className="extract-section"><div><span className="eyebrow">REVIEW BEFORE APPLY</span><h3>서술형 원문에서 조건 후보 찾기</h3><p>선택한 이 자료의 원문을 Gemini에 보냅니다. 값·인용문·원문 줄이 일치한 후보만 저장하며, 검토한 항목만 비교에 반영합니다.</p></div>
 <Button disabled={!canEdit||busy||!health.geminiConfigured||doc.archived} onClick={()=>void post('evidence-extract',{documentId:doc.id}).catch(()=>{})}>{busy?'조건 후보를 찾는 중…':'이 원문으로 AI 조건 추출'}</Button>
 {!health.geminiConfigured&&<p className="form-hint">AI 연결 전에도 항목명이 있는 조건을 규칙으로 비교할 수 있습니다.</p>}
 {doc.extractionDrafts.map(d=>{const chosen=keys[d.id]||d.fields.map(f=>f.key),stale=d.baseVersion!==doc.version;return <article className="extraction-draft" key={d.id}><strong>{d.model} · {d.review==='pending'?'검토 대기':d.review==='applied'?'검토 후 반영':'제외'}</strong>{d.fields.map(f=><label key={f.key} className="extracted-candidate"><input type="checkbox" aria-label={'반영 '+FIELDS.find(k=>k.key===f.key)?.label} checked={chosen.includes(f.key)} disabled={d.review!=='pending'||!canEdit} onChange={e=>setKeys({...keys,[d.id]:e.target.checked?[...chosen,f.key]:chosen.filter(k=>k!==f.key)})}/><span><b>{FIELDS.find(k=>k.key===f.key)?.label}: {f.value}</b><small>L{f.line} · {f.quote}</small></span></label>)}{d.missing.length>0&&<ul>{d.missing.map((x,i)=><li key={i}>{x}</li>)}</ul>}{d.review==='pending'&&<><p className="form-hint">{stale?'원문 또는 검토 조건이 변경되어 이 초안은 반영할 수 없습니다.':'인용이 실제 조건을 뒷받침하는지 확인한 뒤 반영하세요.'}</p><div className="button-group"><Button kind="ghost" disabled={!canEdit||busy} onClick={()=>void act('evidence.extraction.review',{documentId:doc.id,id:d.id,decision:'dismiss'}).catch(()=>{})}>추출 초안 제외</Button><Button disabled={!canEdit||busy||stale||!chosen.length} onClick={()=>void act('evidence.extraction.review',{documentId:doc.id,id:d.id,decision:'apply',expectedVersion:doc.version,keys:chosen}).catch(()=>{})}>검토한 조건 반영</Button></div></>}</article>;})}</section>
 {doc.history.length>0&&<details className="source-details"><summary>보존된 자료 수정 기록 {doc.history.length}개</summary><pre>{JSON.stringify(doc.history,null,2)}</pre></details>}
 </div></Modal>;
}
function DocumentForm({project,document,onClose}:{project:EvidenceProject;document?:EvidenceDocument;onClose:()=>void}){
 const {act,busy,notify}=useLab();const [title,setTitle]=useState(document?.title||''),[text,setText]=useState(document?.text||''),[url,setUrl]=useState(document?.url||''),[kind,setKind]=useState(document?.kind||'note');
 return <Modal title={document?'자료 수정':'자료 등록'} wide onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await act('evidence.document.save',{projectId:project.id,id:document?.id,expectedVersion:document?.version,title,text,url,kind});onClose();}catch{}}}><div className="modal-body"><div className="form-grid"><Field label="자료 제목"><input required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="자료 종류"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kindLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></div><Field label="원문 URL"><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://"/></Field><Field label="자료 원문" hint="최대 40,000자. 항목이 명시된 조건은 규칙으로, 서술형 조건은 AI 추출 후 검토해 사용할 수 있습니다."><textarea required rows={13} maxLength={40000} value={text} onChange={e=>setText(e.target.value)} placeholder={'세포: A549\n물질: 연구 물질\n농도: 1 µM\n시간: 24 h\n측정 방법: ATP\n대조군: 용매 대조군\n반복: 3'}/></Field><label className="file-pick">TXT · Markdown 가져오기<input type="file" accept=".txt,.md,.markdown" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>200000){notify('텍스트 파일은 200 KB 이내로 선택하세요.',true);return;}try{const t=await f.text();if(t.length>40000)throw new Error('자료 원문은 40,000자까지 지원합니다.');setText(t);if(!title)setTitle(f.name);}catch(err){notify((err as Error).message,true);}}}/></label></div><div className="modal-footer"><Button kind="secondary" onClick={onClose}>취소</Button><Button type="submit" disabled={busy}>자료 저장</Button></div></form></Modal>;
}
function ProjectForm({project,onClose,onSaved}:{project?:EvidenceProject;onClose:()=>void;onSaved:(id:string)=>void}){
 const {act,busy}=useLab();const [title,setTitle]=useState(project?.title||''),[goal,setGoal]=useState(project?.goal||''),[templateId,setTemplateId]=useState(project?.templateId||'general'),[conditionLabels,setConditionLabels]=useState('연구 대상\n방법\n비교 기준\n근거');
 return <Modal title={project?'연구 목적 수정':'새 자료 프로젝트'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{const id=await act('evidence.project.save',{id:project?.id,expectedRevision:project?.revision,title,goal,templateId,conditionLabels:conditionLabels.split('\n').map(x=>x.trim()).filter(Boolean)});if(id)onSaved(id);onClose();}catch{}}}><div className="modal-body"><Field label="연구 유형"><select aria-label="연구 유형" disabled={!!project} value={templateId} onChange={e=>setTemplateId(e.target.value)}>{Object.entries(TEMPLATES).map(([key,t])=><option key={key} value={key}>{t.label}</option>)}</select></Field>{templateId==='custom'&&!project&&<Field label="직접 정의할 비교 항목" hint="한 줄에 하나씩, 서로 다른 항목 2~12개를 입력하세요."><textarea rows={6} value={conditionLabels} onChange={e=>setConditionLabels(e.target.value)}/></Field>}<Field label="프로젝트명"><input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="연구 목적"><textarea maxLength={2000} rows={5} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="비교하려는 모델, 조건, 측정 방법과 확인할 질문을 적으세요."/></Field></div><div className="modal-footer"><Button type="submit" disabled={busy}>프로젝트 저장</Button></div></form></Modal>;
}
function Literature({project,onClose}:{project:EvidenceProject;onClose:()=>void}){
 const {act,busy,notify}=useLab();const [query,setQuery]=useState(''),[loading,setLoading]=useState(false),[docs,setDocs]=useState<Partial<EvidenceDocument>[]>([]),[added,setAdded]=useState<string[]>([]);
 return <Modal title="공개 문헌 검색" wide onClose={onClose}><div className="modal-body"><form className="literature-search" onSubmit={async e=>{e.preventDefault();setLoading(true);try{const r=await api<{documents:Partial<EvidenceDocument>[]}>('/literature?q='+encodeURIComponent(query));setDocs(r.documents);}catch(err){notify((err as Error).message,true);}finally{setLoading(false);}}}><Field label="Europe PMC 검색어"><input required minLength={2} maxLength={300} value={query} onChange={e=>setQuery(e.target.value)}/></Field><Button type="submit" disabled={loading}>{loading?'검색 중…':'문헌 검색'}</Button></form><p className="form-hint">검색어가 Europe PMC로 전송됩니다. 가져오는 자료는 공개 초록이며 논문 전체 원문은 아닙니다.</p>{docs.map(d=><article key={d.id} className="literature-result"><h3>{d.title}</h3><p>{d.text?.slice(0,300)}</p><div className="button-group"><a href={d.url} target="_blank" rel="noreferrer">원문 페이지 ↗</a><Button kind="secondary" disabled={busy||added.includes(d.id!)} onClick={()=>void act('evidence.document.save',{projectId:project.id,title:d.title,text:d.text,kind:'paper',url:d.url,abstractOnly:true}).then(()=>setAdded([...added,d.id!])).catch(()=>{})}>{added.includes(d.id!)?'가져옴':'초록 가져오기'}</Button></div></article>)}</div></Modal>;
}

export default function Evidence({view,selectedId}:{view:string;selectedId:string}){
 const {w,act,post,busy,health,canEdit,go,notify}=useLab(),lib=w.evidence;
 const [projectId,setProjectId]=useState(stored('flylabs.v3.project.'+w.id)),[selection,setSelection]=useState<string[]|null>(null),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[mode,setMode]=useState('local'),[routing,setRouting]=useState('connectome'),[showArchived,setShowArchived]=useState(false),[graph,setGraph]=useState<Graph|null>(null);
 const [source,setSource]=useState<{id:string;line:number}|null>(selectedId?{id:selectedId,line:0}:null),[editDoc,setEditDoc]=useState<EvidenceDocument|null|false>(false),[projectModal,setProjectModal]=useState<'new'|'edit'|null>(null),[literature,setLiterature]=useState(false),[base,setBase]=useState(''),[note,setNote]=useState(''),[checks,setChecks]=useState<Record<string,boolean>>({});
 const importFile=useRef<HTMLInputElement>(null);const project=lib.projects.find(p=>p.id===projectId)||lib.projects[0];
 useEffect(()=>{void api<Graph>('/connectome').then(setGraph).catch(()=>{});},[]);
 useEffect(()=>{if(selectedId){const d=lib.documents.find(d=>d.id===selectedId);if(d){setProjectId(d.projectId);setSource({id:d.id,line:0});}}},[selectedId]);
 useEffect(()=>{setSelection(null);setBase('');setChecks({});setNote(project?.planNote||'');},[project?.id]);
 const docs=lib.documents.filter(d=>d.projectId===project?.id&&(showArchived||!d.archived)),active=docs.filter(d=>!d.archived);
 const selected=(selection||project?.selected||[]).filter(id=>active.some(d=>d.id===id)),chosen=active.filter(d=>selected.includes(d.id));
 const comparison=compareDocuments(chosen),run=lib.runs.find(r=>r.projectId===project?.id),stale=!!run&&(run.projectRevision!==project?.revision||Object.entries(run.documentVersions).some(([id,v])=>lib.documents.find(d=>d.id===id)?.version!==v)||chosen.length!==Object.keys(run.documentVersions).length||chosen.some(d=>!Object.hasOwn(run.documentVersions,d.id)));
 const baseDoc=active.find(d=>d.id===base)||active.find(d=>d.id===project?.baseId)||chosen[0]||active[0];
 const FIELDS:ConditionField[]=fieldsFor(project);
 const plan=project&&baseDoc?createPlan(project,baseDoc,note,Object.fromEntries(FIELDS.map(f=>[baseDoc.id+':'+f.key,!!checks[f.key]]))):null;
 const sourceDoc=source?lib.documents.find(d=>d.id===source.id):undefined;
 const filtered=docs.filter(d=>(kind==='all'||d.kind===kind)&&(d.title+' '+d.text).toLowerCase().includes(query.toLowerCase()));
 function chooseProject(id:string){setProjectId(id);storePreference('flylabs.v3.project.'+w.id,id);setSelection(null);setBase('');}
 function toggle(id:string){if(!selected.includes(id)&&selected.length>=8){notify('한 번에 8개 자료까지 비교할 수 있습니다.',true);return;}setSelection(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
 async function analyze(){if(!project)return;try{await post('evidence-run',{projectId:project.id,documentIds:selected,mode,routing});go('compare');}catch{}}
 async function savePreparation(start=false){if(!baseDoc||!project)return;try{const id=await act('evidence.prepare',{projectId:project.id,documentId:baseDoc.id,expectedVersion:baseDoc.version,expectedProjectRevision:project.revision,note,checks});if(start&&id){const eid=await act('evidence.start',{id,date:today()});if(eid)go('notebook',eid);}else notify('출처 원문과 함께 준비표를 보관했습니다.');}catch{}}
 async function startSaved(p:Preparation){try{const eid=await act('evidence.start',{id:p.id,date:today()});if(eid)go('notebook',eid);}catch{}}
 return <>
 <div className="research-context"><div><span className="eyebrow">RESEARCH PROJECT</span><select aria-label="자료 프로젝트" value={project?.id||''} onChange={e=>chooseProject(e.target.value)}>{lib.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div><div className="button-group"><Button kind="ghost" disabled={!canEdit} onClick={()=>setProjectModal('new')}>＋ 새 프로젝트</Button><Button kind="ghost" disabled={!canEdit} onClick={()=>importFile.current?.click()}>기존 JSON 가져오기</Button></div></div>
 <input hidden ref={importFile} type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('백업은 5 MB 이내로 선택하세요.');const workspace=JSON.parse(await f.text());const id=await act('evidence.import',{workspace});if(id)chooseProject(id);notify('자료·준비 메모·랩노트를 원본과 함께 가져왔습니다.');}catch(err){notify((err as Error).message,true);}e.target.value='';}}/>
 {!project?<Empty title="자료에서 첫 실험을 시작하세요" description="새 프로젝트를 만들거나 v1.1.0 JSON 백업을 가져오면 원문과 실험 기록을 이어갈 수 있습니다." action={<Button disabled={!canEdit} onClick={()=>setProjectModal('new')}>첫 자료 프로젝트 만들기</Button>}/>:<>
 {view!=='engine'&&<div className="research-steps">{[['sources','01','자료 모으기'],['compare','02','조건 비교'],['prepare','03','연구 준비'],['notebook','04','기록 이어가기']].map(([id,n,label])=><button key={id} className={view===id?'active':''} onClick={()=>go(id)}><span>{n}</span>{label}<span>→</span></button>)}</div>}
 {view==='evidence'&&<><section className="research-hero"><div><span className="eyebrow">EVIDENCE INTO RESEARCH</span><h1>흩어진 근거를,<br/>다음 연구로.</h1><p>논문·데이터·관찰 기록을 연구에 맞는 기준으로 비교하고,<br/>원문이 연결된 준비표에서 연구를 이어가세요.</p><div className="button-group"><Button onClick={()=>go('sources')}>자료 살펴보기 <Icon name="chevron"/></Button><Button kind="secondary" disabled={!canEdit} onClick={()=>setEditDoc(null)}>자료 등록</Button></div></div><div className="hero-network"><div className="network-caption">CONNECTED RESEARCH <span>MaleCNS · 공개 연결 구조</span></div><Network graph={graph}/><div className="network-foot"><span>자료 → 판단 → 비교 → 준비</span><span>32 nodes / 69 edges</span></div></div></section>
 <div className="evidence-stats">{[['등록 자료',active.length+'','원문과 출처 보관'],['선택한 자료',chosen.length+'','한 번에 최대 8개'],['조건 차이',chosen.length>1?comparison.different+'':'—',FIELDS.length+'개 연구 비교 항목'],['추가 확인',chosen.length?comparison.missing+'':'—','선택 자료에서 빠진 항목']].map(([label,value,hint])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div>
 <section className="panel project-focus"><div><span className="eyebrow">CURRENT QUESTION</span><h2>{project.title}</h2><p>{project.goal||'이 프로젝트에서 확인하려는 연구 질문을 적어 주세요.'}</p><button className="text-button" disabled={!canEdit} onClick={()=>setProjectModal('edit')}>연구 목적 수정 ↗</button></div><div><span className="soft-label">NEXT STEP</span><h3>같은 조건인지 확인해 보세요.</h3><p>차이와 누락 항목을 살펴보고 기준 자료를 선택합니다.</p><Button disabled={!chosen.length} onClick={()=>go('compare')}>선택 자료 비교 →</Button></div></section>
 <div className="section-heading"><h2>최근 자료</h2><button className="text-button" onClick={()=>go('sources')}>전체 자료 보기 →</button></div></>}
 {(view==='sources'||view==='evidence')&&<>{view==='sources'&&<><div className="page-heading"><div><span className="eyebrow">EVIDENCE LIBRARY</span><h1>자료 라이브러리<span className="heading-dot">.</span></h1><p>원문을 보관하고, 비교할 자료를 선택하세요.</p></div><div className="button-group"><Button kind="secondary" disabled={!canEdit||__PUBLIC_DEMO__} onClick={()=>setLiterature(true)}>공개 문헌 검색</Button><Button disabled={!canEdit} onClick={()=>setEditDoc(null)}>＋ 자료 등록</Button></div></div><div className="evidence-toolbar"><label className="evidence-search"><Icon name="search"/><input aria-label="자료 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목, 주제, 방법, 원문 검색"/></label><select aria-label="자료 종류 필터" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">전체 자료</option>{Object.entries(kindLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><label className="check-label"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>보관 자료 포함</label></div><div className="library-summary"><span>{filtered.length}개 자료 · {selected.length}개 비교 선택</span><Button kind="secondary" disabled={!selected.length} onClick={()=>go('compare')}>조건 비교 →</Button></div></>}
 <div className="evidence-cards">{(view==='evidence'?active.slice(0,3):filtered).map(d=>{const fields=extractFields(d);return <article className={'evidence-card '+(d.archived?'archived':'')} key={d.id}><div className="evidence-card-top"><span className="doc-kind">{kindLabels[d.kind]||'자료'}</span><label><input type="checkbox" aria-label={d.title+' 비교 선택'} checked={selected.includes(d.id)} disabled={d.archived} onChange={()=>toggle(d.id)}/>비교</label></div><button className="source-title" onClick={()=>setSource({id:d.id,line:0})}>{d.title}</button><p>{d.text.split('\n').find(l=>l.startsWith('연구 목적:')||l.startsWith('메모:'))||d.text.slice(0,100)}</p><div className="evidence-card-foot"><span>{d.synthetic?'합성 예시':d.abstractOnly?'공개 초록':'등록 원문'} · r{d.version}</span><b>{FIELDS.length-fields.missing.length}/{FIELDS.length} 항목</b></div>{view==='sources'&&canEdit&&<button className="archive-button" onClick={()=>void act('evidence.document.archive',{id:d.id,expectedVersion:d.version,archived:!d.archived}).catch(()=>{})}>{d.archived?'자료 복원':'자료 보관'}</button>}</article>;})}</div>{!filtered.length&&<Empty title="표시할 자료가 없습니다" description="자료를 등록하거나 검색·필터 조건을 변경해 주세요."/>}</>}
 {view==='compare'&&<><div className="page-heading"><div><span className="eyebrow">COMPARE WITH CONTEXT</span><h1>같은 기준인가요<span className="heading-dot">?</span></h1><p>명시된 값과 검토한 조건을 비교합니다. 조건 일치가 결과의 동등성을 뜻하지는 않습니다.</p></div><Button disabled={!chosen.length} onClick={()=>go('prepare')}>연구 준비표 →</Button></div><div className="analysis-controls panel"><div><Field label="자료 판단"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="local">규칙 비교</option><option value="jev" disabled={!health.jevConfigured}>Jev 판단 + 규칙 비교{!health.jevConfigured?' · 연결 필요':''}</option></select></Field><Field label="처리 순서"><select value={routing} onChange={e=>setRouting(e.target.value)}><option value="connectome">커넥텀 구조</option><option value="baseline">일반 순서 · 비교 기준</option></select></Field><Button disabled={!chosen.length||busy||!canEdit} onClick={()=>void analyze()}>{busy?'선택 자료 검토 중…':'비교 실행·기록'}</Button></div><p>{mode==='jev'?'실행하면 선택한 자료의 제목·원문과 연구 목적을 TypeSafe Jev로 전송합니다. 관련성과 맥락 판단은 준비표 채택을 자동 결정하지 않습니다.':'외부 모델에 전송하지 않고 조건·단위·누락을 비교합니다.'}</p></div>
 {!chosen.length?<Empty title="비교할 자료를 선택하세요" action={<Button onClick={()=>go('sources')}>자료 라이브러리</Button>}/>:<><div className="compare-metrics"><span><b>{chosen.length}</b> 선택 자료</span><span><b>{comparison.different}</b> 조건 차이·충돌</span><span><b>{comparison.missing}</b> 추가 확인 항목</span></div><div className="condition-table-wrap"><table className="condition-table"><thead><tr><th>비교 항목</th>{chosen.map(d=><th key={d.id}><button onClick={()=>setSource({id:d.id,line:0})}>{d.title}</button><small>{d.synthetic?'합성 예시 · ':''}r{d.version}</small></th>)}<th>확인 결과</th></tr></thead><tbody>{comparison.rows.map((row:{key:string;label:string;status:string;hasMissing:boolean;values:(EvidenceValue|null)[]})=><tr key={row.key}><th>{row.label}</th>{row.values.map((v:EvidenceValue|null,i:number)=><td key={chosen[i].id}>{v?<button className="evidence-value" onClick={()=>setSource({id:chosen[i].id,line:v.line})}><b>{v.value}</b><small>원문 L{v.line} ↗{v.method==='reviewed-ai'?' · AI 추출 검토됨':''}</small></button>:<span className="missing-value">확인 필요</span>}</td>)}<td><span className={'condition-status '+row.status}>{resultLabels[row.status]}</span>{row.hasMissing&&row.status!=='missing'&&<small>미기재 포함</small>}</td></tr>)}</tbody></table></div><p className="form-hint">단일 농도·시간 값은 단위를 환산합니다. 복합 조건·범위·자유 서술의 의미가 같다는 판단까지 자동화하지 않습니다.</p></>}
 {run&&<section className="panel judgment-panel"><SectionHeading title="최근 실행한 자료 판단"/><div className="panel-body"><p>{new Date(run.createdAt).toLocaleString('ko-KR')} · {run.mode==='jev'?run.model:'규칙 비교'} · {run.routing==='connectome'?'커넥텀 구조':'일반 순서'}</p>{stale&&<div className="inline-note">선택 자료·원문·연구 목적 중 하나가 달라졌습니다. 아래는 이전 실행 기록입니다. 최신 판단은 다시 실행하세요.</div>}{run.judgments.length?run.judgments.map(j=><div className="judgment-row" key={j.id}><strong>{run.sourceSnapshot.find(d=>d.id===j.id)?.title}</strong><span>관련성 {(j.relevance*100).toFixed(0)}%</span><span>대상·방법 명시 {(j.context*100).toFixed(0)}%</span><b>{j.review?'연구자 확인 필요':'원문 검토 후 사용'}</b></div>):<p>외부 AI 판단 없이 규칙으로 실행한 기록입니다.</p>}<p className="form-hint">Jev 수치는 질문에 대한 모델 판단값이며 약효·연구 성공 확률이 아닙니다.</p><button className="text-button" onClick={()=>go('engine')}>처리 순서와 실행 기록 보기 →</button></div></section>}</>}
 {view==='prepare'&&<><div className="page-heading"><div><span className="eyebrow">PREPARE WITH EVIDENCE</span><h1>연구 준비표<span className="heading-dot">.</span></h1><p>하나의 기준 자료에서 시작하고, 확인할 조건과 연구자 메모를 함께 남깁니다.</p></div></div>{plan&&baseDoc?<div className="preparation-layout"><section className="panel"><div className="panel-body"><Field label="기준 자료"><select value={baseDoc.id} onChange={e=>{setBase(e.target.value);setChecks({});}}>{active.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></Field><p>{baseDoc.synthetic?'합성 예시에서 시작하는 준비표입니다.':''}</p><div className="preparation-checks">{FIELDS.map(f=>{const v=plan.fields[f.key];return <label key={f.key}><input type="checkbox" checked={!!checks[f.key]} onChange={e=>setChecks({...checks,[f.key]:e.target.checked})}/><span><b>{f.label}</b><span>{v?.value||'확인 필요'}</span>{v&&<button type="button" className="text-button" onClick={e=>{e.preventDefault();setSource({id:baseDoc.id,line:v.line});}}>원문 L{v.line} ↗</button>}</span></label>;})}</div><Field label="준비표 연구자 메모"><textarea rows={4} maxLength={5000} value={note} onChange={e=>setNote(e.target.value)} placeholder="선택한 조건의 이유와 실제 실험 전 확인할 사항"/></Field><div className="button-group"><Button kind="secondary" disabled={!canEdit||busy} onClick={()=>void savePreparation()}>준비표 저장</Button><Button disabled={!canEdit||busy} onClick={()=>void savePreparation(true)}>저장 후 랩노트 시작</Button></div></div></section><section className="panel preparation-preview"><SectionHeading title="원문이 연결된 준비표" action={<Button kind="ghost" onClick={()=>download('FlyLabs-preparation-v3.1.0.md',planMarkdown(plan),'text/markdown;charset=utf-8')}>Markdown 내보내기</Button>}/><pre>{planMarkdown(plan)}</pre></section></div>:<Empty title="먼저 기준 자료를 등록하세요" action={<Button onClick={()=>go('sources')}>자료 라이브러리</Button>}/>}
 <section className="panel saved-preparations"><SectionHeading title="보관된 준비표"/><div className="panel-body">{lib.preparations.filter(p=>p.projectId===project?.id).map(p=><article key={p.id}><div><h3>{p.sourceSnapshot.title}</h3><p>{new Date(p.createdAt).toLocaleString('ko-KR')} · 원문 r{p.sourceVersion}</p></div><div className="button-group"><Button kind="ghost" onClick={()=>download('FlyLabs-preparation-'+p.id+'.md',p.text)}>내려받기</Button>{p.experimentId?<Button kind="secondary" onClick={()=>go('notebook',p.experimentId)}>연결된 랩노트</Button>:<Button disabled={!canEdit||busy} onClick={()=>void startSaved(p)}>이 준비표로 랩노트 시작</Button>}</div></article>)}{!lib.preparations.some(p=>p.projectId===project?.id)&&<p className="muted">저장하면 당시 원문과 조건이 함께 보관됩니다.</p>}</div></section></>}
 </>}
 {view==='engine'&&<><div className="page-heading"><div><span className="eyebrow">DECISIONS WITH TRACEABLE SOURCES</span><h1>판단과 처리 기록<span className="heading-dot">.</span></h1><p>무엇을 판단했고, 어떤 원문을 어떤 순서로 확인했는지 살펴보세요.</p></div></div><div className="engine-explain"><article className="panel"><span className="eyebrow">01 · STRUCTURED DECISIONS</span><h2>Jev · 질문별 판단</h2><p>자료의 연구 목적 관련성과 연구 대상·방법의 명시 여부를 한 요청의 여러 질문으로 판단합니다. 불확실한 자료에는 추가 확인을 표시합니다.</p><small>관련성 판단을 조건의 과학적 타당성이나 실험 성공으로 해석하지 않습니다.</small><a href="https://docs.typesafe.ai/api" target="_blank" rel="noreferrer">TypeSafe API 문서 ↗</a></article><article className="panel"><span className="eyebrow">02 · CONNECTOME ROUTING</span><h2>연결 구조를 이용한 처리 순서</h2><p>공개 MaleCNS 연결망의 가중치를 전파해 실행 가능한 작업의 우선순위를 정합니다. 조건 추출 후 비교·누락 확인을 진행하는 의존 관계는 항상 지킵니다.</p><small>뉴런과 작업의 대응은 소프트웨어 설계입니다. 일반 순서보다 빠르거나 정확한지는 별도 평가가 필요합니다.</small><a href="https://male-cns.janelia.org/download/" target="_blank" rel="noreferrer">MaleCNS 공개 데이터 · CC BY 4.0 ↗</a></article></div><section className="panel routing-panel"><div className="routing-network"><Network graph={graph}/><p>FlyEM / HHMI Janelia · University of Cambridge · MRC LMB · Google Research</p></div><div><h2>실제로 실행한 작업</h2>{run?<><p>{run.mode==='jev'?run.model:'규칙 비교'} · {run.routing==='connectome'?'커넥텀 구조':'일반 순서'} · {new Date(run.createdAt).toLocaleString('ko-KR')}</p><ol className="trace-list">{run.trace.map(t=><li key={t.id}><b>{t.label}</b><span>{t.count}개 처리 · {t.latencyMs.toFixed(3)} ms</span></li>)}</ol><p className="form-hint">일반 순서: {run.baseline.join(' → ')}</p>{run.providerLatencyMs>0&&<p>Jev 요청 소요: {run.providerLatencyMs.toFixed(0)} ms</p>}</>:<p>조건 비교를 실행하면 작업 순서·처리 개수·시간이 기록됩니다.</p>}</div></section><div className="inline-note">검증 범위: 원문 보존·의존 관계·순서 변경·동일 조건 비교 결과를 확인합니다. 실사용자의 준비 시간과 커넥텀 구조의 성능 이점은 아직 측정 전입니다.</div><section className="panel"><SectionHeading title="프로젝트 실행 이력"/><div className="panel-body">{lib.runs.filter(r=>r.projectId===project?.id).map(r=><details className="run-record" key={r.id}><summary>{new Date(r.createdAt).toLocaleString('ko-KR')} · {r.mode} · {r.routing} · 자료 {r.sourceSnapshot.length}개</summary><p>{r.trace.map(t=>t.label).join(' → ')}</p><p>보존된 원문 버전: {r.sourceSnapshot.map(d=>d.title+' r'+d.version).join(' / ')}</p></details>)}</div></section></>}
 {sourceDoc&&source&&<SourceDialog doc={sourceDoc} line={source.line} onClose={()=>setSource(null)} onEdit={()=>{setEditDoc(sourceDoc);setSource(null);}}/>}
 {editDoc!==false&&project&&<DocumentForm project={project} document={editDoc||undefined} onClose={()=>setEditDoc(false)}/>}
 {projectModal&&<ProjectForm project={projectModal==='edit'?project:undefined} onClose={()=>setProjectModal(null)} onSaved={chooseProject}/>}
 {literature&&project&&<Literature project={project} onClose={()=>setLiterature(false)}/>}
 </>;
}
