import {Fragment,useEffect,useRef,useState} from 'react';
import {useLab} from './context';
import {Button,Empty,Field,Icon,Modal,SectionHeading} from './components';
import {api,download,prettyDate,stored,storePreference,today} from './lib';
import {extractFields,compareDocuments,createPlan,planMarkdown} from '../shared/research.mjs';
import {TEMPLATES,fieldsFor} from '../shared/templates.mjs';
import type {ConditionField,EvidenceDocument,EvidenceProject,EvidenceValue,Preparation} from './types';

type Graph={nodes:{id:string}[];edges:{source:string;target:string;weight:number}[];dataset:string;[key:string]:unknown};
const kindLabels:Record<string,string>={paper:'논문·초록',note:'실험 기록',meeting:'회의 메모',protocol:'프로토콜'};
const resultLabels:Record<string,string>={same:'조건 일치',different:'조건 차이',missing:'확인 필요',conflict:'원문 내 충돌'};
const resultIcons:Record<string,string>={same:'check',different:'differ',missing:'help',conflict:'alert'};
const STATUS_KEYS=['same','different','missing','conflict'];
// v4.0.0: 히어로에서는 연결 구조를 따라 신호가 흐르도록 그립니다. 동작 줄이기 설정이면 정지 화면으로 둡니다.
function Network({graph,tone='light',animate=false}:{graph:Graph|null;tone?:'light'|'hero';animate?:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(!canvas.current||!graph)return;const c=canvas.current,ctx=c.getContext('2d');if(!ctx)return;const width=640,height=380,hero=tone==='hero';c.width=width*2;c.height=height*2;
  const positions=new Map(graph.nodes.map((n,i)=>{const a=i*Math.PI*(3-Math.sqrt(5)),r=34+Math.sqrt(i)*25;return [String(n.id),{x:width/2+Math.cos(a)*r*1.6,y:height/2+Math.sin(a)*r}];}));
  const edges=graph.edges.map(e=>({a:positions.get(String(e.source)),b:positions.get(String(e.target)),w:e.weight})).filter((e):e is {a:{x:number;y:number};b:{x:number;y:number};w:number}=>!!e.a&&!!e.b);
  const base=document.createElement('canvas');base.width=c.width;base.height=c.height;const bx=base.getContext('2d');if(!bx)return;bx.scale(2,2);
  for(const e of edges){bx.strokeStyle=(hero?'rgba(190,180,255,':'rgba(112,96,217,')+Math.min(hero?.42:.38,.08+Math.log(1+e.w)/25)+')';bx.lineWidth=1;bx.beginPath();bx.moveTo(e.a.x,e.a.y);bx.lineTo(e.b.x,e.b.y);bx.stroke();}
  graph.nodes.forEach((n,i)=>{const p=positions.get(String(n.id))!;const key=i<5;if(key){bx.beginPath();bx.arc(p.x,p.y,13,0,Math.PI*2);bx.fillStyle=hero?'rgba(246,196,107,.16)':'rgba(240,160,40,.14)';bx.fill();}bx.beginPath();bx.arc(p.x,p.y,key?6.5:3.6,0,Math.PI*2);bx.fillStyle=key?(hero?'#f6c46b':'#e0962a'):(hero?'#b3a8f7':'#8f80e3');bx.fill();});
  const paint=()=>{ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(base,0,0);};
  paint();
  const still=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(!animate||still)return;
  const routes=[...edges].sort((x,y)=>y.w-x.w).slice(0,16);let frame=0;
  const tick=(t:number)=>{paint();ctx.setTransform(2,0,0,2,0,0);routes.forEach((e,i)=>{const k=((t/2600)+i*.173)%1;const x=e.a.x+(e.b.x-e.a.x)*k,y=e.a.y+(e.b.y-e.a.y)*k,alpha=Math.sin(Math.PI*k);ctx.beginPath();ctx.arc(x,y,2.4,0,Math.PI*2);ctx.fillStyle='rgba(255,226,160,'+(.85*alpha).toFixed(3)+')';ctx.shadowColor='rgba(255,214,130,.9)';ctx.shadowBlur=8;ctx.fill();ctx.shadowBlur=0;});frame=requestAnimationFrame(tick);};
  frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[graph,tone,animate]);return <canvas className="connectome-canvas" ref={canvas} role="img" aria-label="MaleCNS의 32개 뉴런·69개 연결 부분집합. 위치는 화면 표시용이며 해부학적 위치가 아닙니다."/>;
}
type FlowStep={id:string;n:string;label:string;done:boolean;metric:string;detail:string};
const kindIcons:Record<string,string>={paper:'file',note:'flask',meeting:'notes',protocol:'clipboard'};
// 일치율 도넛: 상태별 호 사이에 2px 간격을 두고, 각 호에 이름과 개수를 붙입니다.
function Donut({counts,total}:{counts:Record<string,number>;total:number}){
 const r=70,c=2*Math.PI*r,gap=total>1?3:0;let offset=0;
 return <svg className="donut" viewBox="0 0 180 180" role="img" aria-label={STATUS_KEYS.map(k=>resultLabels[k]+' '+counts[k]+'개').join(', ')}><circle className="donut-track" cx="90" cy="90" r={r}/>{total>0&&STATUS_KEYS.map(k=>{const n=counts[k];if(!n)return null;const len=c*n/total;const seg=<circle key={k} className={'donut-seg '+k} cx="90" cy="90" r={r} strokeDasharray={Math.max(len-gap,1)+' '+(c-Math.max(len-gap,1))} strokeDashoffset={-offset} transform="rotate(-90 90 90)"><title>{resultLabels[k]+' '+n+'개'}</title></circle>;offset+=len;return seg;})}</svg>;
}
function Ring({value,total}:{value:number;total:number}){
 const r=17,c=2*Math.PI*r,p=total?value/total:0;
 return <span className="ring" title={'비교 항목 '+total+'개 중 '+value+'개 확인'}><svg viewBox="0 0 42 42" aria-hidden="true"><circle className="ring-track" cx="21" cy="21" r={r}/><circle className={'ring-fill'+(p===1?' full':'')} cx="21" cy="21" r={r} strokeDasharray={c*p+' '+c} transform="rotate(-90 21 21)"/></svg><b>{value}/{total}</b></span>;
}
function FlowSteps({steps,current,view,go}:{steps:FlowStep[];current:number;view:string;go:(view:string)=>void}){
 return <ol className="flow-steps" aria-label="연구 흐름 진행 상태">{steps.map((s,i)=><li key={s.id} className={(s.done?'done':i===current?'current':'upcoming')+(view===s.id?' active':'')}><button onClick={()=>go(s.id)} aria-current={view===s.id?'step':undefined}><span className="flow-index">{s.done?<Icon name="check"/>:s.n}</span><span className="flow-text"><span className="flow-head"><span className="flow-label">{s.label}</span></span><b>{s.metric}</b></span></button></li>)}</ol>;
}
function SourceDialog({doc,line,onClose,onEdit}:{doc:EvidenceDocument;line:number;onClose:()=>void;onEdit:()=>void}){
 const FIELDS:ConditionField[]=fieldsFor(doc);
 const {post,act,busy,health,canEdit}=useLab();const [keys,setKeys]=useState<Record<string,string[]>>({});
 return <Modal title={doc.title} wide onClose={onClose}><div className="modal-body source-dialog"><div className="source-meta"><span>{kindLabels[doc.kind]||'자료'} · r{doc.version}</span><span>{doc.synthetic?'합성 예시':doc.abstractOnly?'공개 초록':'등록 원문'}</span></div>
 {doc.url&&<a href={doc.url} target="_blank" rel="noreferrer">원문 페이지 열기 ↗</a>}
 <div className="source-lines">{doc.text.split(/\r?\n/).map((t,i)=><div key={i} className={line===i+1?'source-line focused':'source-line'}><span>L{i+1}</span><p>{t||' '}</p></div>)}</div>
 <div className="source-actions"><Button kind="secondary" onClick={()=>download(doc.title+'.txt',doc.text)}>원문 내려받기</Button>{canEdit&&<Button kind="secondary" onClick={onEdit}>자료 수정</Button>}</div>
 <section className="extract-section"><div><span className="eyebrow">REVIEW BEFORE APPLY</span><h3>서술형 원문에서 조건 후보 찾기</h3><p>선택한 이 자료의 원문을 Gemini에 보냅니다. 값·인용문·원문 줄이 일치한 후보만 저장하며, 검토한 항목만 비교에 반영합니다.</p></div>
 <Button disabled={!canEdit||busy||!health.geminiConfigured||doc.archived} onClick={()=>void post('evidence-extract',{documentId:doc.id}).catch(()=>{})}>{busy?'조건 후보를 찾는 중…':'이 원문으로 AI 조건 추출'}</Button>
 {!health.geminiConfigured&&<p className="form-hint">AI 연결 전에도 항목명이 있는 조건을 규칙으로 비교할 수 있습니다.</p>}
 {doc.extractionDrafts.map(d=>{const chosen=keys[d.id]||d.fields.map(f=>f.key),stale=d.baseVersion!==doc.version;return <article className="extraction-draft" key={d.id}><strong>{d.model} · {d.review==='pending'?'검토 대기':d.review==='applied'?'검토 후 반영':'제외'}</strong>{d.fields.map(f=><label key={f.key} className="extracted-candidate"><input type="checkbox" aria-label={'반영 '+FIELDS.find(k=>k.key===f.key)?.label} checked={chosen.includes(f.key)} disabled={d.review!=='pending'||!canEdit} onChange={e=>setKeys({...keys,[d.id]:e.target.checked?[...chosen,f.key]:chosen.filter(k=>k!==f.key)})}/><span><b>{FIELDS.find(k=>k.key===f.key)?.label}: {f.value}</b><small>L{f.line} · {f.quote}</small></span></label>)}{d.missing.length>0&&<ul>{d.missing.map((x,i)=><li key={i}>{x}</li>)}</ul>}{d.review==='pending'&&<><p className="form-hint">{stale?'원문 또는 검토 조건이 변경되어 이 초안은 반영할 수 없습니다.':'인용이 실제 조건을 뒷받침하는지 확인한 뒤 반영하세요.'}</p><div className="button-group"><Button kind="ghost" disabled={!canEdit||busy} onClick={()=>void act('evidence.extraction.review',{documentId:doc.id,id:d.id,decision:'dismiss'}).catch(()=>{})}>추출 초안 제외</Button><Button disabled={!canEdit||busy||stale||!chosen.length} onClick={()=>void act('evidence.extraction.review',{documentId:doc.id,id:d.id,decision:'apply',expectedVersion:doc.version,keys:chosen}).catch(()=>{})}>검토한 조건 반영</Button></div></>}</article>;})}</section>
 {doc.history.length>0&&<details className="source-details"><summary>보존된 자료 수정 기록 {doc.history.length}개</summary><pre>{JSON.stringify(doc.history,null,2)}</pre></details>}
 </div></Modal>;
}
function DocumentForm({project,document,onClose}:{project:EvidenceProject;document?:EvidenceDocument;onClose:()=>void}){
 const {act,busy,notify}=useLab();const [title,setTitle]=useState(document?.title||''),[text,setText]=useState(document?.text||''),[url,setUrl]=useState(document?.url||''),[kind,setKind]=useState(document?.kind||'note');
 return <Modal title={document?'자료 수정':'자료 등록'} wide onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await act('evidence.document.save',{projectId:project.id,id:document?.id,expectedVersion:document?.version,title,text,url,kind});onClose();}catch{}}}><div className="modal-body"><div className="form-grid"><Field label="자료 제목"><input required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="자료 종류"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kindLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></div><Field label="원문 URL"><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://"/></Field><Field label="자료 원문" hint="최대 40,000자. 항목이 명시된 조건은 규칙으로, 서술형 조건은 AI 추출 후 검토해 사용할 수 있습니다."><textarea required rows={13} maxLength={40000} value={text} onChange={e=>setText(e.target.value)} placeholder={'세포: A549\n물질: 연구 물질\n농도: 1 µM\n시간: 24 h\n측정 방법: ATP\n대조군: 용매 대조군\n반복: 3'}/></Field><label className="file-pick">TXT · Markdown 가져오기<input type="file" accept=".txt,.md,.markdown" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>200000){notify('텍스트 파일은 200 KB 이내로 선택하세요.',true);return;}try{const t=await f.text();if(t.length>40000)throw new Error('자료 원문은 40,000자까지 지원합니다.');setText(t);if(!title)setTitle(f.name);}catch(err){notify((err as Error).message,true);}}}/></label></div><div className="modal-footer"><Button kind="secondary" onClick={onClose}>취소</Button><Button type="submit" disabled={busy}>자료 저장</Button></div></form></Modal>;
}
function ProjectForm({project,onClose,onSaved}:{project?:EvidenceProject;onClose:()=>void;onSaved:(id:string)=>void}){
 const {act,busy}=useLab();const [title,setTitle]=useState(project?.title||''),[goal,setGoal]=useState(project?.goal||''),[templateId,setTemplateId]=useState(project?.templateId||'general'),[conditionLabels,setConditionLabels]=useState('연구 대상\n방법\n비교 기준\n근거');
 return <Modal title={project?'연구 목적 수정':'새 자료 프로젝트'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{const id=await act('evidence.project.save',{id:project?.id,expectedRevision:project?.revision,title,goal,templateId,conditionLabels:conditionLabels.split('\n').map(x=>x.trim()).filter(Boolean)});if(id)onSaved(id);onClose();}catch{}}}><div className="modal-body"><Field label="연구 유형"><select aria-label="연구 유형" disabled={!!project} value={templateId} onChange={e=>setTemplateId(e.target.value)}>{Object.entries(TEMPLATES).map(([key,t])=><option key={key} value={key}>{t.label}</option>)}</select></Field>{templateId==='custom'&&!project&&<Field label="직접 정의할 비교 항목" hint="한 줄에 하나씩, 서로 다른 항목 2~12개를 입력하세요."><textarea rows={6} value={conditionLabels} onChange={e=>setConditionLabels(e.target.value)}/></Field>}<Field label="프로젝트명"><input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="연구 목적"><textarea maxLength={2000} rows={5} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="비교하려는 모델, 조건, 측정 방법과 확인할 질문을 적으세요."/></Field></div><div className="modal-footer"><Button type="submit" disabled={busy}>프로젝트 저장</Button></div></form></Modal>;
}
function Literature({project,onClose}:{project:EvidenceProject;onClose:()=>void}){
 const {act,busy,notify}=useLab();const [query,setQuery]=useState(''),[loading,setLoading]=useState(false),[docs,setDocs]=useState<Partial<EvidenceDocument>[]>([]),[added,setAdded]=useState<string[]>([]);
 return <Modal title="공개 문헌 검색" wide onClose={onClose}><div className="modal-body"><form className="literature-search" onSubmit={async e=>{e.preventDefault();setLoading(true);try{const r=await api<{documents:Partial<EvidenceDocument>[]}>('/literature?q='+encodeURIComponent(query));setDocs(r.documents);}catch(err){notify((err as Error).message,true);}finally{setLoading(false);}}}><Field label="Europe PMC 검색어"><input required minLength={2} maxLength={300} value={query} onChange={e=>setQuery(e.target.value)}/></Field><Button type="submit" disabled={loading}>{loading?'검색 중…':'문헌 검색'}</Button></form><p className="form-hint">검색어가 Europe PMC로 전송됩니다. 가져오는 자료는 공개 초록이며 논문 전체 원문은 아닙니다.</p>{docs.map(d=><article key={d.id} className="literature-result"><h3>{d.title}</h3><p>{d.text?.slice(0,300)}</p><div className="button-group"><a href={d.url} target="_blank" rel="noreferrer">원문 페이지 ↗</a><Button kind="secondary" disabled={busy||added.includes(d.id!)} onClick={()=>void act('evidence.document.save',{projectId:project.id,title:d.title,text:d.text,kind:'paper',url:d.url,abstractOnly:true}).then(()=>setAdded([...added,d.id!])).catch(()=>{})}>{added.includes(d.id!)?'가져옴':'초록 가져오기'}</Button></div></article>)}</div></Modal>;
}

export default function Evidence({view,selectedId}:{view:string;selectedId:string}){
 const {w,act,post,busy,health,canEdit,go,notify}=useLab(),lib=w.evidence;
 const [projectId,setProjectId]=useState(stored('flylabs.v3.project.'+w.id)),[selection,setSelection]=useState<string[]|null>(null),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[mode,setMode]=useState('local'),[routing,setRouting]=useState('connectome'),[showArchived,setShowArchived]=useState(false),[graph,setGraph]=useState<Graph|null>(null);
 const [source,setSource]=useState<{id:string;line:number}|null>(selectedId?{id:selectedId,line:0}:null),[editDoc,setEditDoc]=useState<EvidenceDocument|null|false>(false),[projectModal,setProjectModal]=useState<'new'|'edit'|null>(null),[literature,setLiterature]=useState(false),[base,setBase]=useState(''),[note,setNote]=useState(''),[checks,setChecks]=useState<Record<string,boolean>>({}),[heroMenu,setHeroMenu]=useState(false);
 const heroMenuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!heroMenu)return;const close=(e:MouseEvent|KeyboardEvent)=>{if(e instanceof KeyboardEvent?e.key==='Escape':!heroMenuRef.current?.contains(e.target as Node))setHeroMenu(false);};document.addEventListener('mousedown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',close);};},[heroMenu]);
 const importFile=useRef<HTMLInputElement>(null);const project=lib.projects.find(p=>p.id===projectId)||lib.projects[0];
 useEffect(()=>{void api<Graph>('/connectome').then(setGraph).catch(()=>{});},[]);
 useEffect(()=>{if(selectedId){const d=lib.documents.find(d=>d.id===selectedId);if(d){setProjectId(d.projectId);setSource({id:d.id,line:0});}}},[selectedId]);
 useEffect(()=>{setSelection(null);setBase('');setChecks({});setNote(project?.planNote||'');},[project?.id]);
 const docs=lib.documents.filter(d=>d.projectId===project?.id&&(showArchived||!d.archived)),active=docs.filter(d=>!d.archived);
 const selected=(selection||project?.selected||[]).filter(id=>active.some(d=>d.id===id)),chosen=active.filter(d=>selected.includes(d.id));
 const comparison=compareDocuments(chosen),run=lib.runs.find(r=>r.projectId===project?.id),stale=!!run&&(run.projectRevision!==project?.revision||Object.entries(run.documentVersions).some(([id,v])=>lib.documents.find(d=>d.id===id)?.version!==v)||chosen.length!==Object.keys(run.documentVersions).length||chosen.some(d=>!Object.hasOwn(run.documentVersions,d.id)));
 const baseDoc=active.find(d=>d.id===base)||active.find(d=>d.id===project?.baseId)||chosen[0]||active[0];
 const FIELDS:ConditionField[]=fieldsFor(project);
 const plan=project&&baseDoc?createPlan(project,baseDoc,note,Object.fromEntries(FIELDS.map(f=>[baseDoc.id+':'+f.key,!!checks[f.key]]))):null;
 const sourceDoc=source?lib.documents.find(d=>d.id===source.id):undefined;
 const filtered=docs.filter(d=>(kind==='all'||d.kind===kind)&&(d.title+' '+d.text).toLowerCase().includes(query.toLowerCase()));
 const projectRuns=lib.runs.filter(r=>r.projectId===project?.id),projectPreps=lib.preparations.filter(p=>p.projectId===project?.id),notebooks=projectPreps.filter(p=>p.experimentId);
 const statusCounts=Object.fromEntries(STATUS_KEYS.map(k=>[k,chosen.length?comparison.rows.filter((r:{status:string})=>r.status===k).length:0])) as Record<string,number>;
 const flow:FlowStep[]=[{id:'sources',n:'01',label:'자료 모으기',done:active.length>0,metric:active.length+'개 자료',detail:active.length?'원문·출처와 함께 보관':'첫 자료를 등록하세요'},{id:'compare',n:'02',label:'조건 비교',done:projectRuns.length>0||projectPreps.length>0,metric:chosen.length?chosen.length+'개 자료 선택':'선택한 자료 없음',detail:chosen.length>1?'차이 '+comparison.different+' · 추가 확인 '+comparison.missing:'2개 이상 선택하세요'},{id:'prepare',n:'03',label:'연구 준비',done:projectPreps.length>0,metric:'준비표 '+projectPreps.length+'개',detail:projectPreps.length?'당시 원문 스냅샷 보관':'기준 자료와 조건 확정'},{id:'notebook',n:'04',label:'기록 이어가기',done:notebooks.length>0,metric:'랩노트 '+notebooks.length+'개',detail:notebooks.length?'계획·수행·관찰·해석':'준비표에서 시작'}];
 const currentStep=flow.findIndex(s=>!s.done),pendingPrep=projectPreps.find(p=>!p.experimentId),latestNotebook=[...notebooks].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
 const next=currentStep===0?{n:'01',title:'첫 자료를 등록하세요',body:'논문 초록, 실험 기록, 회의 메모를 붙여 넣으면 연구 유형에 맞는 비교 항목을 찾아 정리합니다.',cta:'자료 등록',disabled:!canEdit,action:()=>setEditDoc(null)}
  :currentStep===1?(chosen.length<2?{n:'02',title:'비교할 자료를 2개 이상 고르세요',body:'자료 카드의 ‘비교’를 체크하면 같은 기준으로 조건을 나란히 볼 수 있습니다.',cta:'자료 라이브러리 열기',disabled:false,action:()=>go('sources')}:{n:'02',title:'선택한 '+chosen.length+'개 자료의 조건을 확인하세요',body:FIELDS.length+'개 항목 중 차이 '+comparison.different+'개, 추가 확인 '+comparison.missing+'개를 찾았습니다. 값을 누르면 해당 원문 줄이 열립니다.',cta:'조건 비교 열기',disabled:false,action:()=>go('compare')})
  :currentStep===2?{n:'03',title:'기준 자료로 준비표를 만드세요',body:'확인할 조건을 체크하고 메모를 남기면 당시 원문과 함께 보관됩니다.',cta:'연구 준비표 열기',disabled:false,action:()=>go('prepare')}
  :currentStep===3?{n:'04',title:'준비표로 랩노트를 시작하세요',body:'계획, 실제 수행, 관찰 결과, 해석을 나누어 기록하고 원문 연결을 유지합니다.',cta:pendingPrep?'이 준비표로 랩노트 시작':'연구 준비표 열기',disabled:!!pendingPrep&&(!canEdit||busy),action:()=>{if(pendingPrep)void startSaved(pendingPrep);else go('prepare');}}
  :{n:'✓',title:'랩노트에 결과를 이어서 기록하세요',body:'네 단계를 모두 거쳤습니다. 관찰 결과와 해석을 추가하거나 새 자료로 다음 비교를 시작하세요.',cta:'랩노트 열기',disabled:false,action:()=>go('notebook',latestNotebook?.experimentId)};
 const when=(at:string)=>new Date(at).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
 const activity=[...projectRuns.map(r=>({id:r.id,at:r.createdAt,icon:'compare',title:'조건 비교 기록',detail:(r.mode==='jev'?r.model:'규칙 비교')+' · 자료 '+r.sourceSnapshot.length+'개',action:()=>go('engine')})),...projectPreps.map(p=>({id:p.id,at:p.createdAt,icon:'clipboard',title:'준비표 보관',detail:p.sourceSnapshot.title,action:()=>go('prepare')})),...notebooks.map(p=>({id:p.id+'-notebook',at:p.createdAt,icon:'notebook',title:'랩노트 시작',detail:p.sourceSnapshot.title,action:()=>go('notebook',p.experimentId)}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,4);
 const previewRows=[...comparison.rows].sort((a:{status:string},b:{status:string})=>['conflict','different','missing','same'].indexOf(a.status)-['conflict','different','missing','same'].indexOf(b.status)) as {key:string;label:string;status:string;values:(EvidenceValue|null)[]}[],previewDocs=chosen.slice(0,3);
 const issues=previewRows.filter(r=>r.status!=='same'),sames=previewRows.filter(r=>r.status==='same');
 const focus=chosen.length>1&&(currentStep===0||currentStep===1)?issues[0]:undefined,focusIndex=focus?focus.values.findIndex(v=>!!v):-1;
 const labActive=w.experiments.filter(e=>e.status!=='completed'),labAttention=labActive.filter(e=>e.status==='blocked'||(w.issues[e.id]||[]).length>0),labPending=w.notes.filter(n=>n.review==='pending'),todayReservations=w.reservations.filter(r=>r.start.slice(0,10)===today()).sort((a,b)=>a.start.localeCompare(b.start));
 const labStats=[{label:'진행 중인 실험',value:labActive.length,icon:'flask',tone:'',action:()=>go('experiments')},{label:'확인이 필요한 실험',value:labAttention.length,icon:'alert',tone:labAttention.length?'warn':'',action:()=>go('today')},{label:'검토할 변경안',value:labPending.length,icon:'notes',tone:'',action:()=>go('notes')},{label:'오늘 장비 예약',value:todayReservations.length,icon:'calendar',tone:'',action:()=>go('resources')}];
 const docRow=(d:EvidenceDocument)=>{const fields=extractFields(d),filled=FIELDS.length-fields.missing.length,isSelected=selected.includes(d.id);return <li className={'doc-row'+(isSelected?' is-selected':'')} key={d.id}><span className="doc-icon"><Icon name={kindIcons[d.kind]||'file'}/></span><span className="doc-main"><button className="doc-title" onClick={()=>setSource({id:d.id,line:0})} title={d.title}>{d.title}</button><small>{kindLabels[d.kind]||'자료'} · {d.synthetic?'합성 예시':d.abstractOnly?'공개 초록':'등록 원문'} · r{d.version}</small></span><Ring value={filled} total={FIELDS.length}/><label className="compare-toggle"><input type="checkbox" aria-label={d.title+' 비교 선택'} checked={isSelected} disabled={d.archived} onChange={()=>toggle(d.id)}/>비교</label></li>;};
 const card=(d:EvidenceDocument)=>{const fields=extractFields(d),filled=FIELDS.length-fields.missing.length,isSelected=selected.includes(d.id);return <article className={'evidence-card'+(d.archived?' archived':'')+(isSelected?' is-selected':'')} key={d.id}><div className="evidence-card-top"><span className="doc-kind">{kindLabels[d.kind]||'자료'}</span><label className="compare-toggle"><input type="checkbox" aria-label={d.title+' 비교 선택'} checked={isSelected} disabled={d.archived} onChange={()=>toggle(d.id)}/>비교</label></div><button className="source-title" onClick={()=>setSource({id:d.id,line:0})}>{d.title}</button><p>{d.text.split('\n').find(l=>l.startsWith('연구 목적:')||l.startsWith('메모:'))||d.text.slice(0,100)}</p><div className="evidence-card-foot"><span>{d.synthetic?'합성 예시':d.abstractOnly?'공개 초록':'등록 원문'} · r{d.version}</span><span className="fill-meter" aria-hidden="true"><i style={{width:(FIELDS.length?filled/FIELDS.length*100:0)+'%'}}/></span><b>{filled}/{FIELDS.length} 항목</b></div>{view==='sources'&&canEdit&&<button className="archive-button" onClick={()=>void act('evidence.document.archive',{id:d.id,expectedVersion:d.version,archived:!d.archived}).catch(()=>{})}>{d.archived?'자료 복원':'자료 보관'}</button>}</article>;};
 function chooseProject(id:string){setProjectId(id);storePreference('flylabs.v3.project.'+w.id,id);setSelection(null);setBase('');}
 function toggle(id:string){if(!selected.includes(id)&&selected.length>=8){notify('한 번에 8개 자료까지 비교할 수 있습니다.',true);return;}setSelection(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
 async function analyze(){if(!project)return;try{await post('evidence-run',{projectId:project.id,documentIds:selected,mode,routing});go('compare');}catch{}}
 async function savePreparation(start=false){if(!baseDoc||!project)return;try{const id=await act('evidence.prepare',{projectId:project.id,documentId:baseDoc.id,expectedVersion:baseDoc.version,expectedProjectRevision:project.revision,note,checks});if(start&&id){const eid=await act('evidence.start',{id,date:today()});if(eid)go('notebook',eid);}else notify('출처 원문과 함께 준비표를 보관했습니다.');}catch{}}
 async function startSaved(p:Preparation){try{const eid=await act('evidence.start',{id:p.id,date:today()});if(eid)go('notebook',eid);}catch{}}
 return <>
 {(view!=='evidence'||!project)&&<div className="research-context"><div className="project-switch"><span className="eyebrow">연구 프로젝트{project?' · '+(TEMPLATES[project.templateId as keyof typeof TEMPLATES]?.label||'범용 연구'):''}</span><div className="project-select"><span className="select-sizer" aria-hidden="true">{project?.title}</span><select aria-label="자료 프로젝트" value={project?.id||''} onChange={e=>chooseProject(e.target.value)}>{lib.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><Icon name="down"/></div></div><div className="button-group"><Button kind="ghost" disabled={!canEdit} onClick={()=>setProjectModal('new')}><Icon name="plus"/>새 프로젝트</Button><Button kind="ghost" disabled={!canEdit} onClick={()=>importFile.current?.click()}><Icon name="upload"/>기존 JSON 가져오기</Button></div></div>}
 <input hidden ref={importFile} type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('백업은 5 MB 이내로 선택하세요.');const workspace=JSON.parse(await f.text());const id=await act('evidence.import',{workspace});if(id)chooseProject(id);notify('자료·준비 메모·랩노트를 원본과 함께 가져왔습니다.');}catch(err){notify((err as Error).message,true);}e.target.value='';}}/>
 {!project?<Empty title="자료에서 첫 실험을 시작하세요" description="새 프로젝트를 만들거나 v1.1.0 JSON 백업을 가져오면 원문과 실험 기록을 이어갈 수 있습니다." action={<Button disabled={!canEdit} onClick={()=>setProjectModal('new')}>첫 자료 프로젝트 만들기</Button>}/>:<>
 {['sources','compare','prepare'].includes(view)&&<FlowSteps steps={flow} current={currentStep} view={view} go={go}/>}
 {view==='evidence'&&<div className="bento">
 <section className="tile tile-hero">
  <div className="hero-art" aria-hidden="true"><Network graph={graph} tone="hero" animate/></div>
  <div className="hero-head"><div className="hero-project"><span className="hero-eyebrow">연구 프로젝트 · {TEMPLATES[project.templateId as keyof typeof TEMPLATES]?.label||'범용 연구'}</span><div className="project-select on-dark"><span className="select-sizer" aria-hidden="true">{project.title}</span><select aria-label="자료 프로젝트" value={project.id} onChange={e=>chooseProject(e.target.value)}>{lib.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><Icon name="down"/></div><p className="hero-goal">{project.goal||'이 프로젝트에서 확인하려는 연구 질문을 적어 주세요.'} <button className="hero-link" disabled={!canEdit} onClick={()=>setProjectModal('edit')}>연구 목적 수정</button></p></div>
  <div className="hero-side"><div className="hero-actions" ref={heroMenuRef}><button className="hero-btn primary" disabled={!canEdit} onClick={()=>setEditDoc(null)}><Icon name="plus"/>자료 등록</button><button className="hero-btn icon-only" aria-label="프로젝트 메뉴" aria-haspopup="menu" aria-expanded={heroMenu} onClick={()=>setHeroMenu(!heroMenu)}><Icon name="more"/></button>{heroMenu&&<div className="hero-menu" role="menu"><button role="menuitem" disabled={!canEdit} onClick={()=>{setHeroMenu(false);setProjectModal('new');}}><Icon name="layers"/>새 프로젝트</button><button role="menuitem" disabled={!canEdit} onClick={()=>{setHeroMenu(false);importFile.current?.click();}}><Icon name="upload"/>기존 JSON 가져오기</button></div>}</div></div></div>
  <ol className="pipeline" aria-label="연구 흐름 진행 상태">{flow.map((st,i)=>{const state=st.done?'done':i===currentStep?'current':'upcoming';return <li key={st.id} className={state+(i>0&&flow[i-1].done?' lead-done':'')}><button onClick={()=>go(st.id)}><span className="pipe-node">{st.done?<Icon name="check"/>:<b>{st.n}</b>}</span><span className="pipe-label">{st.label}{state==='current'&&<em>지금</em>}</span><strong>{st.metric}</strong><small>{st.detail}</small></button></li>;})}</ol>
  <div className="hero-foot"><h1>흩어진 근거를, 다음 연구로.</h1><span>같은 기준으로 비교하고, 원문이 연결된 준비표로 잇습니다.</span><span className="hero-dataset">MaleCNS 연결 구조 · 32 nodes · 69 edges</span></div>
 </section>
 <section className="tile tile-next"><span className="next-kicker"><span className="next-num">{next.n}</span>지금 할 일</span><h2>{focus?'선택한 자료에서 '+(focus.status==='missing'?'빠진 조건':'조건 차이')+'를 찾았습니다':next.title}</h2>
  {focus&&<button className="insight" onClick={()=>{if(focusIndex>=0)setSource({id:previewDocs[focusIndex].id,line:focus.values[focusIndex]!.line});}}><span className="insight-label">{focus.label} · {resultLabels[focus.status]}</span><span className="insight-values">{focus.values.slice(0,3).map((v,i)=><Fragment key={i}>{i>0&&<i aria-hidden="true">{focus.status==='different'?'↔':'·'}</i>}<b className={v?'':'is-missing'}>{v?v.value:'미기재'}</b></Fragment>)}</span><span className="insight-source">근거 원문 {focusIndex>=0?'L'+focus.values[focusIndex]!.line:''} 열기<Icon name="external"/></span></button>}
  <p>{next.body}</p><button className="next-cta" disabled={next.disabled} onClick={next.action}>{next.cta}<Icon name="arrow"/></button></section>
 <section className="tile tile-match"><div className="tile-head"><div><h2>조건 일치율</h2><span>{chosen.length?'자료 '+chosen.length+'개 · 비교 항목 '+FIELDS.length+'개':'비교할 자료를 선택하세요'}</span></div></div>
  <div className="donut-wrap"><Donut counts={statusCounts} total={chosen.length?FIELDS.length:0}/><div className="donut-center"><strong>{chosen.length?statusCounts.same:'–'}<span>/{FIELDS.length}</span></strong><small>항목 일치</small></div></div>
  <ul className="match-legend">{STATUS_KEYS.map(k=><li key={k} className={k+(statusCounts[k]?'':' is-zero')}><Icon name={resultIcons[k]}/>{resultLabels[k]}<b>{statusCounts[k]}</b></li>)}</ul><p className="match-note"><Icon name="info"/>명시된 값과 단위가 같다는 뜻입니다. 결과가 같다는 판단은 아닙니다.</p></section>
 <section className="tile tile-diff"><div className="tile-head"><div><h2>차이부터 보기</h2><span>값을 누르면 근거가 된 원문 줄이 열립니다</span></div><button className="tile-link" disabled={!chosen.length} onClick={()=>go('compare')}>전체 비교<Icon name="arrow"/></button></div>
  {chosen.length?<><ul className="diff-docs">{previewDocs.map((d,i)=><li key={d.id}><span className="doc-letter">{'ABC'[i]}</span><button onClick={()=>setSource({id:d.id,line:0})} title={d.title}>{d.title}</button></li>)}{chosen.length>3&&<li className="diff-more">외 {chosen.length-3}개</li>}</ul>
  <div className="diff-rows">{issues.map(row=><div key={row.key} className={'diff-row is-'+row.status}><div className="diff-label"><b>{row.label}</b><span className={'status-chip '+row.status}><Icon name={resultIcons[row.status]}/>{resultLabels[row.status]}</span></div><div className="diff-values">{row.values.slice(0,3).map((v,i)=><Fragment key={i}>{i>0&&<span className="diff-sep" aria-hidden="true"><Icon name={row.status==='different'?'differ':row.status==='missing'?'help':'alert'}/></span>}{v?<button className="diff-value" onClick={()=>setSource({id:previewDocs[i].id,line:v.line})} title={'원문 '+v.line+'번째 줄 열기'}><span className="doc-letter">{'ABC'[i]}</span><b>{v.value}</b><small>L{v.line}</small></button>:<span className="diff-value is-missing"><span className="doc-letter">{'ABC'[i]}</span><b>미기재</b></span>}</Fragment>)}</div></div>)}{!issues.length&&<p className="diff-allsame"><Icon name="check"/>선택한 자료의 {FIELDS.length}개 항목이 모두 일치합니다.</p>}</div>
  {sames.length>0&&<div className="same-block"><span className="same-title"><Icon name="check"/>일치한 항목 {sames.length}개</span><ul className="same-chips">{sames.map(row=>{const texts=[...new Set(row.values.filter((v):v is EvidenceValue=>!!v).map(v=>v.value))];return <li key={row.key}><b>{row.label}</b><span>{texts.join(' = ')}</span>{texts.length>1&&<em>단위 환산</em>}</li>;})}</ul></div>}</>
  :<Empty title="비교할 자료를 선택하세요" description="자료 타일에서 ‘비교’를 2개 이상 체크하면 다른 조건부터 보여 드립니다." action={<Button kind="secondary" onClick={()=>go('sources')}>자료 라이브러리</Button>}/>}</section>
 <section className="tile tile-docs"><div className="tile-head"><div><h2>자료<span className="count">{active.length}</span></h2><span>비교 선택 {chosen.length}개 · 한 번에 최대 8개</span></div><button className="tile-link" onClick={()=>go('sources')}>자료 라이브러리<Icon name="arrow"/></button></div>
  {active.length?<ul className="doc-list">{active.slice(0,4).map(docRow)}</ul>:<Empty title="아직 등록한 자료가 없습니다" description="논문 초록, 실험 기록, 회의 메모를 등록해 비교를 시작하세요." action={<Button disabled={!canEdit} onClick={()=>setEditDoc(null)}>자료 등록</Button>}/>}
  {active.length>4&&<button className="doc-more" onClick={()=>go('sources')}>나머지 {active.length-4}개 자료 보기<Icon name="chevron"/></button>}</section>
 <section className="tile tile-lab"><div className="tile-head"><div><h2>연구실 현황</h2><span>{prettyDate(today(),true)}</span></div><button className="tile-link" onClick={()=>go('today')}>오늘의 연구실<Icon name="arrow"/></button></div>
  <div className="lab-stats">{labStats.map(st=><button key={st.label} className={'lab-stat'+(st.tone?' tone-'+st.tone:'')} onClick={st.action}><span className="lab-icon"><Icon name={st.icon}/></span><strong>{st.value}</strong><span>{st.label}</span></button>)}</div>
  <div className="lab-agenda"><span className="agenda-title">오늘 장비 일정</span>{todayReservations.length?todayReservations.slice(0,3).map(r=><button key={r.id} className="agenda-item" onClick={()=>go('experiments',r.experimentId)}><time>{r.start.slice(11)}</time><span><b>{w.resources.find(x=>x.id===r.resourceId)?.name}</b><small>{w.experiments.find(e=>e.id===r.experimentId)?.code} · {w.members.find(m=>m.id===r.ownerId)?.name} · ~{r.end.slice(11)}</small></span><Icon name="chevron"/></button>):<p className="agenda-empty">오늘은 예약된 장비가 없습니다.</p>}</div></section>
 {activity.length>0&&<section className="tile tile-activity"><div className="tile-head"><div><h2>최근 활동</h2><span>원문 버전과 함께 보관된 기록입니다</span></div>{projectRuns.length>0&&<button className="tile-link" onClick={()=>go('engine')}>처리 기록<Icon name="arrow"/></button>}</div><ol className="activity-list">{activity.map(a=><li key={a.id}><button onClick={a.action}><span className="activity-icon"><Icon name={a.icon}/></span><span className="activity-text"><b>{a.title}</b><small>{a.detail}</small></span><time dateTime={a.at}>{when(a.at)}</time></button></li>)}</ol></section>}
 </div>}
 {view==='sources'&&<><><div className="page-heading"><div><span className="eyebrow">EVIDENCE LIBRARY</span><h1>자료 라이브러리<span className="heading-dot">.</span></h1><p>원문을 보관하고, 비교할 자료를 선택하세요.</p></div><div className="button-group"><Button kind="secondary" disabled={!canEdit||__PUBLIC_DEMO__} onClick={()=>setLiterature(true)}>공개 문헌 검색</Button><Button disabled={!canEdit} onClick={()=>setEditDoc(null)}>＋ 자료 등록</Button></div></div><div className="evidence-toolbar"><label className="evidence-search"><Icon name="search"/><input aria-label="자료 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목, 주제, 방법, 원문 검색"/></label><select aria-label="자료 종류 필터" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">전체 자료</option>{Object.entries(kindLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><label className="check-label"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>보관 자료 포함</label></div><div className="library-summary"><span>{filtered.length}개 자료 · {selected.length}개 비교 선택</span><Button kind="secondary" disabled={!selected.length} onClick={()=>go('compare')}>조건 비교 →</Button></div></>
 <div className="evidence-cards">{filtered.map(card)}</div>{!filtered.length&&<Empty title="표시할 자료가 없습니다" description="자료를 등록하거나 검색·필터 조건을 변경해 주세요."/>}</>}
 {view==='compare'&&<><div className="page-heading"><div><span className="eyebrow">COMPARE WITH CONTEXT</span><h1>같은 기준인가요<span className="heading-dot">?</span></h1><p>명시된 값과 검토한 조건을 비교합니다. 조건 일치가 결과의 동등성을 뜻하지는 않습니다.</p></div><Button disabled={!chosen.length} onClick={()=>go('prepare')}>연구 준비표 →</Button></div><div className="analysis-controls panel"><div><Field label="자료 판단"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="local">규칙 비교</option><option value="jev" disabled={!health.jevConfigured}>Jev 판단 + 규칙 비교{!health.jevConfigured?' · 연결 필요':''}</option></select></Field><Field label="처리 순서"><select value={routing} onChange={e=>setRouting(e.target.value)}><option value="connectome">커넥텀 구조</option><option value="baseline">일반 순서 · 비교 기준</option></select></Field><Button disabled={!chosen.length||busy||!canEdit} onClick={()=>void analyze()}>{busy?'선택 자료 검토 중…':'비교 실행·기록'}</Button></div><p>{mode==='jev'?'실행하면 선택한 자료의 제목·원문과 연구 목적을 TypeSafe Jev로 전송합니다. 관련성과 맥락 판단은 준비표 채택을 자동 결정하지 않습니다.':'외부 모델에 전송하지 않고 조건·단위·누락을 비교합니다.'}</p></div>
 {!chosen.length?<Empty title="비교할 자료를 선택하세요" action={<Button onClick={()=>go('sources')}>자료 라이브러리</Button>}/>:<><div className="compare-metrics"><span><b>{chosen.length}</b> 선택 자료</span><span><b>{comparison.different}</b> 조건 차이·충돌</span><span><b>{comparison.missing}</b> 추가 확인 항목</span></div><div className="condition-table-wrap"><table className="condition-table"><thead><tr><th>비교 항목</th>{chosen.map(d=><th key={d.id}><button onClick={()=>setSource({id:d.id,line:0})}>{d.title}</button><small>{d.synthetic?'합성 예시 · ':''}r{d.version}</small></th>)}<th>확인 결과</th></tr></thead><tbody>{comparison.rows.map((row:{key:string;label:string;status:string;hasMissing:boolean;values:(EvidenceValue|null)[]})=><tr key={row.key} className={'is-'+row.status}><th>{row.label}</th>{row.values.map((v:EvidenceValue|null,i:number)=><td key={chosen[i].id}>{v?<button className="evidence-value" onClick={()=>setSource({id:chosen[i].id,line:v.line})}><b>{v.value}</b><small>원문 L{v.line} ↗{v.method==='reviewed-ai'?' · AI 추출 검토됨':''}</small></button>:<span className="missing-value">확인 필요</span>}</td>)}<td><span className={'condition-status '+row.status}><Icon name={resultIcons[row.status]}/>{resultLabels[row.status]}</span>{row.hasMissing&&row.status!=='missing'&&<small>미기재 포함</small>}</td></tr>)}</tbody></table></div><p className="form-hint">단일 농도·시간 값은 단위를 환산합니다. 복합 조건·범위·자유 서술의 의미가 같다는 판단까지 자동화하지 않습니다.</p></>}
 {run&&<section className="panel judgment-panel"><SectionHeading title="최근 실행한 자료 판단"/><div className="panel-body"><p>{new Date(run.createdAt).toLocaleString('ko-KR')} · {run.mode==='jev'?run.model:'규칙 비교'} · {run.routing==='connectome'?'커넥텀 구조':'일반 순서'}</p>{stale&&<div className="inline-note">선택 자료·원문·연구 목적 중 하나가 달라졌습니다. 아래는 이전 실행 기록입니다. 최신 판단은 다시 실행하세요.</div>}{run.judgments.length?run.judgments.map(j=><div className="judgment-row" key={j.id}><strong>{run.sourceSnapshot.find(d=>d.id===j.id)?.title}</strong><span>관련성 {(j.relevance*100).toFixed(0)}%</span><span>대상·방법 명시 {(j.context*100).toFixed(0)}%</span><b>{j.review?'연구자 확인 필요':'원문 검토 후 사용'}</b></div>):<p>외부 AI 판단 없이 규칙으로 실행한 기록입니다.</p>}<p className="form-hint">Jev 수치는 질문에 대한 모델 판단값이며 약효·연구 성공 확률이 아닙니다.</p><button className="text-button" onClick={()=>go('engine')}>처리 순서와 실행 기록 보기 →</button></div></section>}</>}
 {view==='prepare'&&<><div className="page-heading"><div><span className="eyebrow">PREPARE WITH EVIDENCE</span><h1>연구 준비표<span className="heading-dot">.</span></h1><p>하나의 기준 자료에서 시작하고, 확인할 조건과 연구자 메모를 함께 남깁니다.</p></div></div>{plan&&baseDoc?<div className="preparation-layout"><section className="panel"><div className="panel-body"><Field label="기준 자료"><select value={baseDoc.id} onChange={e=>{setBase(e.target.value);setChecks({});}}>{active.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></Field><p>{baseDoc.synthetic?'합성 예시에서 시작하는 준비표입니다.':''}</p><div className="preparation-checks">{FIELDS.map(f=>{const v=plan.fields[f.key];return <label key={f.key}><input type="checkbox" checked={!!checks[f.key]} onChange={e=>setChecks({...checks,[f.key]:e.target.checked})}/><span><b>{f.label}</b><span>{v?.value||'확인 필요'}</span>{v&&<button type="button" className="text-button" onClick={e=>{e.preventDefault();setSource({id:baseDoc.id,line:v.line});}}>원문 L{v.line} ↗</button>}</span></label>;})}</div><Field label="준비표 연구자 메모"><textarea rows={4} maxLength={5000} value={note} onChange={e=>setNote(e.target.value)} placeholder="선택한 조건의 이유와 실제 실험 전 확인할 사항"/></Field><div className="button-group"><Button kind="secondary" disabled={!canEdit||busy} onClick={()=>void savePreparation()}>준비표 저장</Button><Button disabled={!canEdit||busy} onClick={()=>void savePreparation(true)}>저장 후 랩노트 시작</Button></div></div></section><section className="panel preparation-preview"><SectionHeading title="원문이 연결된 준비표" action={<Button kind="ghost" onClick={()=>download('FlyLabs-preparation-v3.1.0.md',planMarkdown(plan),'text/markdown;charset=utf-8')}>Markdown 내보내기</Button>}/><pre>{planMarkdown(plan)}</pre></section></div>:<Empty title="먼저 기준 자료를 등록하세요" action={<Button onClick={()=>go('sources')}>자료 라이브러리</Button>}/>}
 <section className="panel saved-preparations"><SectionHeading title="보관된 준비표"/><div className="panel-body">{lib.preparations.filter(p=>p.projectId===project?.id).map(p=><article key={p.id}><div><h3>{p.sourceSnapshot.title}</h3><p>{new Date(p.createdAt).toLocaleString('ko-KR')} · 원문 r{p.sourceVersion}</p></div><div className="button-group"><Button kind="ghost" onClick={()=>download('FlyLabs-preparation-'+p.id+'.md',p.text)}>내려받기</Button>{p.experimentId?<Button kind="secondary" onClick={()=>go('notebook',p.experimentId)}>연결된 랩노트</Button>:<Button disabled={!canEdit||busy} onClick={()=>void startSaved(p)}>이 준비표로 랩노트 시작</Button>}</div></article>)}{!lib.preparations.some(p=>p.projectId===project?.id)&&<p className="muted">저장하면 당시 원문과 조건이 함께 보관됩니다.</p>}</div></section></>}
 </>}
 {view==='engine'&&<><div className="page-heading"><div><span className="eyebrow">DECISIONS WITH TRACEABLE SOURCES</span><h1>판단과 처리 기록<span className="heading-dot">.</span></h1><p>무엇을 판단했고, 어떤 원문을 어떤 순서로 확인했는지 살펴보세요.</p></div></div><div className="engine-explain"><article className="panel"><span className="eyebrow">01 · STRUCTURED DECISIONS</span><h2>Jev · 질문별 판단</h2><p>자료의 연구 목적 관련성과 연구 대상·방법의 명시 여부를 한 요청의 여러 질문으로 판단합니다. 불확실한 자료에는 추가 확인을 표시합니다.</p><small>관련성 판단을 조건의 과학적 타당성이나 실험 성공으로 해석하지 않습니다.</small><a href="https://docs.typesafe.ai/api" target="_blank" rel="noreferrer">TypeSafe API 문서 ↗</a></article><article className="panel"><span className="eyebrow">02 · CONNECTOME ROUTING</span><h2>연결 구조를 이용한 처리 순서</h2><p>공개 MaleCNS 연결망의 가중치를 전파해 실행 가능한 작업의 우선순위를 정합니다. 조건 추출 후 비교·누락 확인을 진행하는 의존 관계는 항상 지킵니다.</p><small>뉴런과 작업의 대응은 소프트웨어 설계입니다. 일반 순서보다 빠르거나 정확한지는 별도 평가가 필요합니다.</small><a href="https://male-cns.janelia.org/download/" target="_blank" rel="noreferrer">MaleCNS 공개 데이터 · CC BY 4.0 ↗</a></article></div><section className="panel routing-panel"><div className="routing-network"><Network graph={graph} tone="hero" animate/><p>FlyEM / HHMI Janelia · University of Cambridge · MRC LMB · Google Research</p></div><div><h2>실제로 실행한 작업</h2>{run?<><p>{run.mode==='jev'?run.model:'규칙 비교'} · {run.routing==='connectome'?'커넥텀 구조':'일반 순서'} · {new Date(run.createdAt).toLocaleString('ko-KR')}</p><ol className="trace-list">{run.trace.map(t=><li key={t.id}><b>{t.label}</b><span>{t.count}개 처리 · {t.latencyMs.toFixed(3)} ms</span></li>)}</ol><p className="form-hint">일반 순서: {run.baseline.join(' → ')}</p>{run.providerLatencyMs>0&&<p>Jev 요청 소요: {run.providerLatencyMs.toFixed(0)} ms</p>}</>:<p>조건 비교를 실행하면 작업 순서·처리 개수·시간이 기록됩니다.</p>}</div></section><div className="inline-note">검증 범위: 원문 보존·의존 관계·순서 변경·동일 조건 비교 결과를 확인합니다. 실사용자의 준비 시간과 커넥텀 구조의 성능 이점은 아직 측정 전입니다.</div><section className="panel"><SectionHeading title="프로젝트 실행 이력"/><div className="panel-body">{lib.runs.filter(r=>r.projectId===project?.id).map(r=><details className="run-record" key={r.id}><summary>{new Date(r.createdAt).toLocaleString('ko-KR')} · {r.mode} · {r.routing} · 자료 {r.sourceSnapshot.length}개</summary><p>{r.trace.map(t=>t.label).join(' → ')}</p><p>보존된 원문 버전: {r.sourceSnapshot.map(d=>d.title+' r'+d.version).join(' / ')}</p></details>)}</div></section></>}
 {sourceDoc&&source&&<SourceDialog doc={sourceDoc} line={source.line} onClose={()=>setSource(null)} onEdit={()=>{setEditDoc(sourceDoc);setSource(null);}}/>}
 {editDoc!==false&&project&&<DocumentForm project={project} document={editDoc||undefined} onClose={()=>setEditDoc(false)}/>}
 {projectModal&&<ProjectForm project={projectModal==='edit'?project:undefined} onClose={()=>setProjectModal(null)} onSaved={chooseProject}/>}
 {literature&&project&&<Literature project={project} onClose={()=>setLiterature(false)}/>}
 </>;
}
