import { useState } from 'react';
import { useLab } from './context';
import { Avatar, Button, Empty, Icon, SectionHeading } from './components';
import { CATEGORY, STATUS, type Note } from './types';
import { prettyDate, shortTime } from './lib';
export function NoteCard({note:n,showExperiment=false}:{note:Note;showExperiment?:boolean}) {
  const {w,go,act,busy:requestBusy,canEdit}=useLab();const busy=requestBusy||!canEdit;const exp=w.experiments.find(e=>e.id===n.experimentId);
  const stale=n.review==='pending'&&exp&&w.notes.find(x=>x.id===n.id) && (n as Note & {expectedUpdatedAt?:string}).expectedUpdatedAt!==exp.updatedAt;
  return <article className="note-card"><div className="note-meta"><Avatar small person={w.members.find(m=>m.id===n.authorId)}/><strong>{w.members.find(m=>m.id===n.authorId)?.name}</strong><span>{prettyDate(n.createdAt)} · {shortTime(n.createdAt)}</span><span className={'source-tag '+n.source}>{n.source==='jev'?'Jev 판단':n.source==='rules'?'규칙 점검':'직접 기록'}</span></div>{showExperiment&&<button className="note-experiment" onClick={()=>go('experiments',n.experimentId)}>{exp?.code} · {exp?.title}<Icon name="chevron"/></button>}<p className="note-text">{n.text}</p><div className="note-tags"><span>{CATEGORY[n.category]||'기타 기록'}</span>{typeof n.confidence==='number'&&<span>모델 신뢰도 {Math.round(n.confidence*100)}%</span>}{n.stale&&<span>저장 중 실험이 변경되어 제안 생략</span>}</div>{n.review==='pending'&&n.proposal&&<div className="proposal"><span className="proposal-icon"><Icon name="spark"/></span><div><strong>상태 변경 제안 · {STATUS[n.proposal.status]}</strong><p>{stale?'이후 실험이 변경되었습니다. 이 제안을 제외하고 최신 기록으로 다시 확인해 주세요.':n.source==='rules'?'메모의 명시적 표현을 기준으로 만든 제안입니다. 원문을 확인해 주세요.':'선택한 메모에 대한 Jev 판단입니다. 원문을 확인한 뒤 반영해 주세요.'}</p></div><div className="proposal-actions"><Button kind="ghost" disabled={busy} onClick={()=>void act('note.review',{id:n.id,decision:'dismiss'}).catch(()=>{})}>제외</Button><Button kind="secondary" disabled={busy||!!stale} onClick={()=>void act('note.review',{id:n.id,decision:'apply'}).catch(()=>{})}>반영</Button></div></div>}{n.review==='applied'&&<div className="review-status"><Icon name="check"/>검토 후 상태에 반영했습니다.</div>}{n.review==='dismissed'&&<div className="review-status muted">변경 제안 제외 · 원문 기록은 보존됩니다.</div>}</article>;
}
export default function Notes() {
  const {w,open}=useLab();const [filter,setFilter]=useState('all'),[query,setQuery]=useState('');
  const rows=w.notes.filter(n=>(filter==='all'||n.review==='pending')&&n.text.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-heading"><div><div className="eyebrow">LAB NOTEBOOK</div><h1>흐름이 되는 연구 기록<span className="heading-dot">.</span></h1><p>짧은 메모와 검토한 변경이, 실험의 맥락으로 쌓입니다.</p></div><Button disabled={!w.experiments.length} onClick={()=>open({type:'note'})}><Icon name="plus"/>진행 기록</Button></div><section className="panel"><div className="list-toolbar"><div className="tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>모든 기록 <span>{w.notes.length}</span></button><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>검토 대기 <span>{w.notes.filter(n=>n.review==='pending').length}</span></button></div><label className="inline-search"><Icon name="search"/><input aria-label="기록 검색" placeholder="기록 내용 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="notebook-feed">{rows.map(n=><NoteCard key={n.id} note={n} showExperiment/>)}{!rows.length&&<Empty title={filter==='pending'?'검토할 변경안이 없습니다':'표시할 기록이 없습니다'} description="실험의 진행 상황과 변경 사항을 남겨 보세요."/>}</div></section><section className="panel history-panel"><SectionHeading title="최근 변경 이력"/><div className="audit-list">{w.audit.slice(0,15).map(a=><div className="audit-row" key={a.id}><span className="audit-marker"/><div><strong>{a.action}</strong><p>{a.detail}</p></div><span>{w.members.find(m=>m.id===a.actorId)?.name}<small>{prettyDate(a.createdAt)} {shortTime(a.createdAt)}</small></span></div>)}</div></section></>;
}
