import {useEffect,useState,useRef} from 'react';
import {useLab} from './context';
import {Avatar,Button,Empty,Field,Icon,Modal,SectionHeading} from './components';
import {api,download,prettyDate,shortTime} from './lib';
import type {Experiment,NotebookFields,AIDraft,NotebookHistory} from './types';
const labels:Record<string,string>={objective:'연구 목적',hypothesis:'가설 / 연구 질문',design:'실험 설계',materials:'시료·재료·조건',procedure:'실행 절차',observations:'관찰 결과',analysis:'분석·해석',conclusion:'결론',limitations:'한계·미확인 사항',nextSteps:'다음 단계'};
const hints:Record<string,string>={objective:'이 실험으로 무엇을 확인하려고 하나요?',hypothesis:'검증할 가설 또는 답하려는 질문을 적으세요.',design:'비교군, 반복, 변수, 분석 기준을 직접 정리하세요.',materials:'시료 ID, 배치, 재료, 확인한 조건과 단위를 기록하세요.',procedure:'사용한 절차의 버전과 실제 진행 내용을 기록하세요.',observations:'측정값과 눈으로 확인한 사실을 적으세요. 해석은 다음 항목에 분리합니다.',analysis:'관찰 결과가 질문에 대해 무엇을 의미하는지 정리하세요.',conclusion:'현재 근거로 말할 수 있는 결론을 적으세요.',limitations:'누락된 측정, 불확실성, 추가 확인 사항을 적으세요.',nextSteps:'다음에 확인하거나 진행할 일을 정리하세요.'};
function DraftReview({draft:d,exp}:{draft:AIDraft;exp:Experiment}){
 const {act,busy,w,canEdit}=useLab(),[selected,setSelected]=useState(Object.keys(d.fields));
 const stale=d.baseRevision!==exp.notebook.revision;
 return <article className="ai-draft"><div className="draft-heading"><span className="soft-label"><Icon name="spark"/>{d.kind==='plan'?'계획 정리':'결과 정리'} · AI 초안</span><small>{d.model} · {prettyDate(d.createdAt)} {shortTime(d.createdAt)}</small></div>
 {Object.entries(d.fields).map(([key,value])=><div className="draft-field" key={key}><label><input type="checkbox" checked={selected.includes(key)} disabled={d.review!=='pending'||!canEdit} onChange={e=>setSelected(old=>e.target.checked?[...old,key]:old.filter(k=>k!==key))}/><strong>{labels[key]}</strong></label>{exp.notebook.fields[key]&&<details><summary>현재 기록 보기</summary><p>{exp.notebook.fields[key]}</p></details>}<p>{value||'(빈 항목)'}</p></div>)}
 {d.missing.length>0&&<div className="missing-inputs"><b>추가 확인이 필요한 내용</b><ul>{d.missing.map((m,i)=><li key={i}>{m}</li>)}</ul></div>}
 <details className="source-details"><summary>사용한 원문과 출처 {d.citations.length}개</summary>{d.sourceSnapshot.filter(s=>d.citations.includes(s.id)).map(s=><div key={s.id}><code>{s.name||s.id}</code><pre>{s.text}</pre></div>)}</details>
 {d.review==='pending'?<div className="draft-review-footer"><p>{stale?'노트가 변경되어 이 초안은 반영할 수 없습니다. 최신 내용으로 다시 생성하세요.':'선택한 항목을 위 초안으로 교체합니다. 근거와 수치를 검토한 뒤 반영하세요.'}</p><Button kind="ghost" disabled={busy||!canEdit} onClick={()=>void act('ai.dismiss',{experimentId:exp.id,id:d.id}).catch(()=>{})}>초안 제외</Button><Button disabled={busy||!canEdit||stale||!!exp.notebook.signed||!selected.length} onClick={()=>void act('ai.apply',{experimentId:exp.id,id:d.id,expectedRevision:exp.notebook.revision,fieldKeys:selected,reason:'AI 초안 검토 후 선택 항목 반영'}).catch(()=>{})}>선택 항목 반영</Button></div>:<div className="review-status">{d.review==='applied'?'검토 후 반영된 초안':'제외한 초안'} · 원문과 이력을 보존합니다.</div>}
 </article>;
}
export function NotebookEditor({exp}:{exp:Experiment}){
 const {w,act,busy,post,notify,health,canEdit,user}=useLab(),n=exp.notebook;
 const [tab,setTab]=useState('plan'),[editing,setEditing]=useState(false),[form,setForm]=useState<NotebookFields>({...n.fields}),[base,setBase]=useState(n.revision),[reason,setReason]=useState(''),[entry,setEntry]=useState(''),[amends,setAmends]=useState(''),[aiText,setAiText]=useState(''),[aiKind,setAiKind]=useState('plan'),[includeNotebook,setIncludeNotebook]=useState(true),[includeEntries,setIncludeEntries]=useState(true),[fileIds,setFileIds]=useState<string[]>([]),[history,setHistory]=useState<NotebookHistory|null>(null),[sign,setSign]=useState(false),[reopening,setReopening]=useState(false),[reopenReason,setReopenReason]=useState(''),[restored,setRestored]=useState(false);
 const localKey='flylabs.v3.draft.'+user.id+'.'+w.id+'.'+exp.id;
 
 useEffect(()=>{if(!editing){setForm({...n.fields});setBase(n.revision);}},[n.revision,editing]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing]);
 useEffect(()=>{if(editing){try{sessionStorage.setItem(localKey,JSON.stringify({fields:form,revision:base,reason}));}catch{}}},[form,base,reason,editing]);
 function startEdit(){let saved;try{saved=JSON.parse(sessionStorage.getItem(localKey)||'null');}catch{}if(saved){setForm(saved.fields);setBase(saved.revision);setReason(saved.reason||'');setRestored(true);}else{setForm({...n.fields});setBase(n.revision);setReason('');}setEditing(true);}
 async function save(){try{await act('notebook.save',{experimentId:exp.id,fields:form,expectedRevision:base,reason:reason||'노트 작성'});sessionStorage.removeItem(localKey);setEditing(false);setRestored(false);}catch{}}
 async function exportNote(){try{const r=await api<{text:string}>('/workspaces/'+w.id+'/notebook/'+exp.id);download(exp.code+'-notebook-r'+n.revision+'.md',r.text,'text/markdown;charset=utf-8');}catch(e){notify((e as Error).message,true);}}
 const pending=n.aiDrafts.filter(d=>d.review==='pending').length,groups=tab==='results'?['observations','analysis','conclusion','limitations','nextSteps']:['objective','hypothesis','design','materials','procedure'];
 return <section className="notebook-area"><div className="notebook-toolbar"><div><span className="eyebrow">EXPERIMENT NOTEBOOK</span><h2>계획부터 결론까지, 이 실험의 기록</h2><p>리비전 {n.revision} · {n.signed?'서명됨 · 편집 잠금':'작성 중'}{n.updatedAt?' · '+new Date(n.updatedAt).toLocaleString('ko-KR'):''}</p></div><div className="button-group"><Button kind="secondary" onClick={()=>void exportNote()}><Icon name="download"/>노트 내보내기</Button>{canEdit&&!n.signed&&!editing&&<Button onClick={startEdit}><Icon name="note"/>노트 작성</Button>}{canEdit&&n.signed&&<Button kind="secondary" onClick={()=>setReopening(true)}>새 리비전 열기</Button>}</div></div>
 <div className="panel"><div className="tabs notebook-tabs">{[['plan','실험 계획'],['results','결과·해석'],['entries','실행 기록 '+n.entries.length],['ai','AI 도우미'+(pending?' · '+pending:'')],['history','수정 이력']].map(([k,v])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {n.signed&&<div className="signed-notice"><Icon name="check"/>{w.members.find(m=>m.id===n.signed?.authorId)?.name} · {new Date(n.signed.createdAt).toLocaleString('ko-KR')} · 리비전 {n.signed.revision} 확인 서명</div>}
 {(tab==='plan'||tab==='results')&&<div className="notebook-fields">{editing&&<div className="inline-note">{restored?'이 탭에 임시 보관된 작성 내용을 복구했습니다. ':''}작성 중인 내용은 이 브라우저 탭에 임시 보관합니다. 기록 반영은 ‘노트 저장’으로 완료하세요.{base!==n.revision&&<p><b>새로 저장된 리비전이 있습니다.</b> 내 작성 내용을 복사한 뒤 편집을 취소하고 최신 기록을 확인하세요.</p>}</div>}{groups.map(key=><div key={key} className="notebook-field"><div><span className="field-number">{String(Object.keys(labels).indexOf(key)+1).padStart(2,'0')}</span><h3>{labels[key]}</h3></div>{editing?<textarea aria-label={labels[key]} rows={key==='procedure'||key==='observations'?6:4} maxLength={20000} value={form[key]||''} placeholder={hints[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<p className={n.fields[key]?'':'unwritten'}>{n.fields[key]||hints[key]}</p>}</div>)}{editing?<div className="notebook-save"><Field label="수정 이유"><input maxLength={300} placeholder="예: 대조군과 분석 기준 추가" value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="button-group"><Button kind="secondary" disabled={busy} onClick={()=>{setEditing(false);setRestored(false);sessionStorage.removeItem(localKey);}}>편집 취소</Button><Button disabled={busy||base!==n.revision} onClick={()=>void save()}>노트 저장</Button></div></div>:canEdit&&!n.signed&&<div className="notebook-save"><p>작성한 목적·관찰·결론을 검토한 뒤 이 리비전을 서명할 수 있습니다.</p><Button kind="secondary" onClick={()=>setSign(true)}>검토 후 서명</Button></div>}</div>}
 {tab==='entries'&&<div className="entries-panel">{canEdit&&!n.signed&&<form onSubmit={async e=>{e.preventDefault();try{await act('entry.add',{experimentId:exp.id,text:entry,amendsId:amends||undefined});setEntry('');setAmends('');}catch{}}}><Field label={amends?'정정 내용':'실행 기록'} hint="저장 후 원문은 유지됩니다. 정정할 때는 새 기록을 원문에 연결합니다."><textarea required maxLength={10000} rows={4} placeholder="실제로 수행한 작업, 변경한 조건, 관찰한 사실을 시간 순서대로 남기세요." value={entry} onChange={e=>setEntry(e.target.value)}/></Field>{amends&&<div className="inline-note">정정 대상: {n.entries.find(e=>e.id===amends)?.text}<button className="text-button" type="button" onClick={()=>setAmends('')}>정정 취소</button></div>}<Button type="submit" disabled={busy}>실행 기록 저장</Button></form>}<div className="entry-feed">{n.entries.map(e=><article key={e.id}><div className="note-meta"><Avatar person={w.members.find(m=>m.id===e.authorId)} small/><strong>{w.members.find(m=>m.id===e.authorId)?.name}</strong><span>{new Date(e.createdAt).toLocaleString('ko-KR')}</span>{canEdit&&!n.signed&&<button className="text-button" onClick={()=>{setAmends(e.id);setEntry('');}}>정정 기록 추가</button>}</div>{e.amendsId&&<span className="soft-label">이전 기록 정정 · {e.amendsId.slice(0,8)}</span>}<p className="note-text">{e.text}</p></article>)}{!n.entries.length&&<Empty title="실제 수행한 내용을 남겨 보세요" description="계획과 실제 실행 사이의 차이가 다음 실험의 중요한 단서가 됩니다."/>}</div></div>}
 {tab==='ai'&&<div className="ai-panel"><div className="ai-intro"><span className="focus-symbol"><Icon name="spark"/></span><div><h3>흩어진 메모를, 검토할 수 있는 초안으로.</h3><p>계획과 결과를 나누고 입력된 근거만 정리합니다. 빠진 정보는 질문으로 남깁니다.</p></div></div>{canEdit&&!n.signed&&<form onSubmit={async e=>{e.preventDefault();try{await post('assistant',{experimentId:exp.id,kind:aiKind,text:aiText,includeNotebook,includeEntries,fileIds});setAiText('');}catch{}}}><div className="form-grid"><Field label="AI 작업"><select value={aiKind} onChange={e=>setAiKind(e.target.value)}><option value="plan">실험 계획 정리</option><option value="results">결과·해석 초안 정리</option></select></Field><div className="provider-label">Gemini · {health.generationModel}</div></div><Field label="정리할 원문" hint="실험 조건, 관찰 결과, 확인할 질문을 적으세요. AI가 없는 측정값을 만들도록 요청하지 마세요."><textarea rows={5} maxLength={12000} value={aiText} onChange={e=>setAiText(e.target.value)} placeholder="예: 목적은 두 이미지 분석 방법의 일치도 확인. 동일한 이미지 12장을 두 방법으로 분석할 계획. 임계값과 비교 지표는 아직 정하지 않음."/></Field><fieldset className="ai-source-picker"><legend>AI에 제공할 기록</legend><label><input type="checkbox" checked={includeNotebook} onChange={e=>setIncludeNotebook(e.target.checked)}/>현재 랩노트 항목</label><label><input type="checkbox" checked={includeEntries} onChange={e=>setIncludeEntries(e.target.checked)}/>최근 실행 기록 20개</label>{w.files.filter(f=>f.experimentId===exp.id&&f.size<=100000&&/\.(txt|md|csv|tsv|json)$/i.test(f.name)).map(f=><label key={f.id}><input type="checkbox" checked={fileIds.includes(f.id)} onChange={e=>setFileIds(old=>e.target.checked?[...old,f.id]:old.filter(x=>x!==f.id))}/>{f.name}</label>)}</fieldset><div className="ai-consent"><p>클릭하면 선택한 원문·기록·파일 내용이 Google Gemini로 전송됩니다. 선택하지 않은 파일은 전송하지 않습니다. 생성된 초안은 검토 후 선택한 항목에만 반영합니다.</p><Button type="submit" disabled={busy||!health.geminiConfigured||editing}>{busy?'AI 요청 처리 중…':'선택한 내용으로 초안 생성'}</Button></div>{editing&&<p className="form-hint">작성 중인 노트를 먼저 저장하거나 편집을 취소하세요.</p>}</form>}{n.aiDrafts.map(d=><DraftReview key={d.id} draft={d} exp={exp}/>)}{!health.geminiConfigured&&<div className="inline-note">Gemini 연결이 필요합니다. 직접 작성과 Jev 상태 판단은 별도 기능입니다.</div>}</div>}
 {tab==='history'&&<div className="history-panel notebook-history"><p className="form-hint">저장 전 항목과 수정 이유를 보존합니다. 실행 기록은 별도의 추가·정정 이력으로 남습니다.</p>{n.history.map((h,i)=><button key={h.id} className="history-row" onClick={()=>setHistory(h)}><Icon name="note"/><span><strong>리비전 {h.revision}{h.signed?' · 서명 기록':''}</strong><small>{h.reason} · {w.members.find(m=>m.id===h.authorId)?.name} · {new Date(h.createdAt).toLocaleString('ko-KR')}</small></span><Icon name="chevron"/></button>)}{!n.history.length&&<Empty title="첫 기록을 저장하면 이력이 남습니다"/>}</div>}</div>
 {history&&<Modal title={'리비전 '+history.revision+' · 보존된 기록'} wide onClose={()=>setHistory(null)}><div className="modal-body history-preview">{Object.entries(labels).map(([k,v])=><section key={k}><h3>{v}</h3><p>{history.fields[k]||'미작성'}</p></section>)}</div></Modal>}
 {sign&&<Modal title="이 리비전 검토 후 서명" onClose={()=>!busy&&setSign(false)}><div className="modal-body"><p>리비전 {n.revision}의 목적·관찰·결론을 확인했음을 {__PUBLIC_DEMO__?'이 브라우저의 확인 기록으로 남깁니다.':user.name+' 계정으로 기록합니다.'} 서명 후 노트 항목과 실행 기록, 파일 추가가 잠깁니다.</p><p className="form-hint">{__PUBLIC_DEMO__?'이 체험판의 확인 기록에는 계정 인증이 없습니다.':'이는 앱 내 계정 확인 서명입니다.'} 공인 전자서명이나 규제 준수 인증을 의미하지 않습니다. 수정은 이유를 남기고 새 리비전에서 이어갈 수 있습니다.</p></div><div className="modal-footer"><Button kind="secondary" onClick={()=>setSign(false)} disabled={busy}>취소</Button><Button disabled={busy} onClick={()=>void act('notebook.sign',{experimentId:exp.id,expectedRevision:n.revision}).then(()=>setSign(false)).catch(()=>{})}>확인하고 서명</Button></div></Modal>}
 {reopening&&<Modal title="새 리비전 열기" onClose={()=>!busy&&setReopening(false)}><form onSubmit={async e=>{e.preventDefault();try{await act('notebook.reopen',{experimentId:exp.id,reason:reopenReason,expectedRevision:n.revision});setReopening(false);setReopenReason('');}catch{}}}><div className="modal-body"><Field label="수정을 재개하는 이유"><textarea required maxLength={300} value={reopenReason} onChange={e=>setReopenReason(e.target.value)}/></Field><p className="form-hint">기존 서명과 내용을 이력에 보존하고 새 리비전을 시작합니다.</p></div><div className="modal-footer"><Button type="submit" disabled={busy}>새 리비전 열기</Button></div></form></Modal>}
 </section>;
}
export default function Notebook({selected}:{selected:string}){
 const {w,go,open,canEdit}=useLab(),[query,setQuery]=useState('');
 const exp=w.experiments.find(e=>e.id===selected);
 if(exp)return <><button className="back-link" onClick={()=>go('notebook')}><Icon name="back"/>전체 랩노트</button><div className="page-heading"><div><div className="eyebrow">{exp.code} · {exp.project}</div><h1>{exp.title}</h1><p>{w.members.find(m=>m.id===exp.ownerId)?.name} · {exp.date}</p></div><Button kind="secondary" onClick={()=>go('experiments',exp.id)}>준비·파일 관리<Icon name="chevron"/></Button></div><NotebookEditor exp={exp}/></>;
 const rows=w.experiments.filter(e=>[e.title,e.project,...Object.values(e.notebook.fields)].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-heading"><div><div className="eyebrow">YOUR RESEARCH, IN CONTEXT</div><h1>랩노트<span className="heading-dot">.</span></h1><p>실험 계획과 실행, 관찰과 해석을 연결하는 연구 기록.</p></div><Button disabled={!canEdit} onClick={()=>open({type:'experiment'})}><Icon name="plus"/>새 실험·노트</Button></div><label className="notebook-search"><Icon name="search"/><input aria-label="랩노트 검색" placeholder="실험명, 프로젝트, 노트 내용 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="notebook-grid">{rows.map(e=>{const n=e.notebook,filled=Object.values(n.fields).filter(Boolean).length;return <button className="notebook-card" key={e.id} onClick={()=>go('notebook',e.id)}><div><span className="eyebrow">{e.code} · {e.project}</span><span className={'soft-label '+(n.signed?'signed':'')}>{n.signed?'서명됨':'작성 중'}</span></div><h2>{e.title}</h2><p>{n.fields.objective||e.description||'실험의 목적부터 기록해 보세요.'}</p><div className="notebook-card-progress"><span style={{width:filled/10*100+'%'}}/></div><footer><span>{filled}/10 항목 · 실행 기록 {n.entries.length}</span><span>r{n.revision}<Icon name="chevron"/></span></footer></button>;})}</div>{!rows.length&&<Empty title="첫 실험 노트를 만들어 보세요" description="한 실험의 계획부터 결과까지 함께 기록할 수 있습니다."/>}</>;
}
