import {useState,useEffect} from 'react';
import { useLab } from './context';
import { Avatar, Button, Field, Icon, SectionHeading,Modal } from './components';
import { api, send, download, today } from './lib';
export default function Settings() {
 const {w,health,open,notify,user,refresh,changeWorkspace}=useLab(),owner=w.myRole==='owner';
 const [invitations,setInvitations]=useState<{id:string;email:string;role:string;expiresAt:number}[]>([]);
 useEffect(()=>{if(owner)void api<typeof invitations>('/workspaces/'+w.id+'/invitations').then(setInvitations).catch(()=>{});},[w.id,w.revision,owner]);
 const [email,setEmail]=useState(''),[role,setRole]=useState('editor'),[invite,setInvite]=useState(''),[working,setWorking]=useState(false),[token,setToken]=useState(''),[password,setPassword]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[remove,setRemove]=useState<{id:string;name:string}|null>(null);
 async function exportData(){try{const data=await api<unknown>('/workspaces/'+w.id+'/export');download('FlyLabs-workspace-'+today()+'.json',JSON.stringify(data,null,2),'application/json');notify('연구실 기록을 내보냈습니다.');}catch(err){notify((err as Error).message,true);}}
 async function permission(userId:string,nextRole:string){setWorking(true);try{await send('/workspaces/'+w.id+'/permissions',{userId,role:nextRole});await refresh();setRemove(null);notify('접근 권한을 변경했습니다.');}catch(e){notify((e as Error).message,true);}finally{setWorking(false);}}
 return <><div className="page-heading"><div><div className="eyebrow">YOUR WORKSPACE</div><h1>연구실과 계정 설정<span className="heading-dot">.</span></h1><p>같은 기록을 이어갈 동료와, 각자의 접근 권한을 관리합니다.</p></div><span className="soft-label">TEAM NOTEBOOK · v{health.version}</span></div><div className="settings-grid">
 <section className="panel"><SectionHeading title="작업 공간"/><div className="panel-body"><div className="workspace-identity"><span className="workspace-icon"><Icon name="flask"/></span><div><h3>{w.name}</h3><p>{w.kind==='academic'?'학계 연구실':'바이오텍 R&D'} · {owner?'관리자':w.myRole==='editor'?'편집자':'열람자'}</p></div></div><p>연구실별로 실험·랩노트·자원·파일을 분리합니다. 초대된 계정만 이 공간에 접근할 수 있습니다.</p><Button kind="secondary" onClick={()=>open({type:'workspace'})}><Icon name="plus"/>새 연구실 만들기</Button><form className="accept-invite" onSubmit={async e=>{e.preventDefault();setWorking(true);try{const value=token.includes('#invite/')?token.split('#invite/')[1]:token;const r=await send<{workspaceId:string}>('/invitations/accept',{token:value.trim()});setToken('');changeWorkspace(r.workspaceId);notify('연구실에 참여했습니다.');}catch(e){notify((e as Error).message,true);}finally{setWorking(false);}}}><Field label="받은 초대 링크"><input required value={token} onChange={e=>setToken(e.target.value)} placeholder="초대 링크를 붙여 넣으세요."/></Field><Button kind="secondary" type="submit" disabled={working}>초대 수락</Button></form></div></section>
 <section className="panel"><SectionHeading title="AI 연결"/><div className="panel-body"><div className="provider-card"><b>Jev <span className={'connection '+(health.jevConfigured?'connected':'')}>{health.jevConfigured?'설정됨':'미연결'}</span></b><p>진행 메모의 의미를 판단해 상태 변경을 제안합니다.</p><code>{health.model}</code></div><div className="provider-card"><b>Gemini <span className={'connection '+(health.geminiConfigured?'connected':'')}>{health.geminiConfigured?'설정됨':'미연결'}</span></b><p>선택한 원문·노트·텍스트 파일을 바탕으로 계획과 결과 초안을 정리합니다.</p><code>{health.generationModel}</code></div><p className="form-hint">키는 서버에서만 읽습니다. ‘설정됨’은 연결 정보의 존재를 뜻하며, API 응답은 요청 시 확인됩니다. 전송 범위는 각 AI 작업 화면에서 선택합니다. 오류가 나면 원문을 유지하며 다른 제공자로 자동 전환하지 않습니다.</p></div></section>
 <section className="panel"><SectionHeading title="구성원과 권한" count={w.access.length} action={owner&&<button className="text-button" onClick={()=>open({type:'member'})}>외부 담당자 등록</button>}/><div className="member-list">{w.members.map(m=>{const a=w.access.find(a=>a.memberId===m.id);return <div key={m.id}><Avatar person={m}/><span><strong>{m.name}</strong><small>{a?a.role==='owner'?'관리자':a.role==='editor'?'편집 권한':'열람 권한':m.userId?'이전 구성원 · 접근 없음':'외부 담당자 · 로그인 없음'}</small></span>{a&&owner&&a.role!=='owner'&&<div className="member-permissions"><select aria-label={m.name+' 권한'} value={a.role} disabled={working} onChange={e=>void permission(a.userId,e.target.value)}><option value="editor">편집자</option><option value="viewer">열람자</option></select><button className="text-button" onClick={()=>setRemove({id:a.userId,name:m.name})}>접근 해제</button></div>}</div>;})}</div>{owner&&<form className="invite-form" onSubmit={async e=>{e.preventDefault();setWorking(true);try{const r=await send<{token:string}>('/workspaces/'+w.id+'/invitations',{email,role});setInvite(location.origin+'/#invite/'+r.token);notify('7일 동안 사용할 수 있는 초대 링크를 만들었습니다.');await refresh();}catch(e){notify((e as Error).message,true);}finally{setWorking(false);}}}><div className="form-grid"><Field label="초대할 이메일"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="초대 권한"><select value={role} onChange={e=>setRole(e.target.value)}><option value="editor">편집자 · 작성과 수정</option><option value="viewer">열람자 · 읽기와 내보내기</option></select></Field></div><Button type="submit" disabled={working}><Icon name="people"/>초대 링크 만들기</Button>{invite&&<div className="invite-result"><Field label="생성된 초대 링크"><input readOnly value={invite}/></Field><Button kind="secondary" onClick={()=>void navigator.clipboard.writeText(invite).then(()=>notify('초대 링크를 복사했습니다.')).catch(()=>notify('링크를 선택해 직접 복사해 주세요.',true))}>링크 복사</Button><p>초대받은 이메일 계정에서 한 번만 수락할 수 있습니다. 링크를 동료에게 직접 전달하세요. 메일은 자동 발송하지 않습니다.</p></div>}</form>}{owner&&invitations.length>0&&<div className="pending-invitations"><h3>참여 대기 중인 초대</h3>{invitations.map(i=><div key={i.id}><span>{i.email}<small>{i.role==='editor'?'편집자':'열람자'} · {new Date(i.expiresAt).toLocaleDateString('ko-KR')}까지</small></span><button className="text-button" disabled={working} onClick={async()=>{setWorking(true);try{await send('/workspaces/'+w.id+'/invitations/revoke',{id:i.id});setInvite('');await refresh();notify('초대 링크를 취소했습니다.');}catch(e){notify((e as Error).message,true);}finally{setWorking(false);}}}>초대 취소</button></div>)}</div>}</section>
 <section className="panel"><SectionHeading title="내 계정"/><div className="panel-body"><div className="account-details"><strong>{user.name}</strong><span>{user.email}</span></div><p>작성자와 수정 이력은 로그인한 계정으로 기록됩니다.</p><form onSubmit={async e=>{e.preventDefault();setWorking(true);try{await send('/auth/password',{currentPassword,password});setCurrentPassword('');setPassword('');notify('비밀번호를 변경했습니다. 다른 세션은 종료되었습니다.');}catch(e){notify((e as Error).message,true);}finally{setWorking(false);}}}><Field label="현재 비밀번호"><input required type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></Field><Field label="새 비밀번호" hint="12자 이상, 최대 200자"><input required type="password" autoComplete="new-password" minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)}/></Field><Button kind="secondary" type="submit" disabled={working}>비밀번호 변경</Button></form></div></section>
 <section className="panel"><SectionHeading title="연구 기록 보관"/><div className="panel-body"><h3>노트와 원본 파일을 함께 보관하세요.</h3><p>개별 노트는 랩노트 화면에서 Markdown으로 내려받을 수 있습니다. 연구실 전체 기록은 JSON으로 내보냅니다.</p><Button kind="secondary" onClick={()=>void exportData()}><Icon name="download"/>연구실 기록 내보내기</Button><p className="form-hint">JSON은 기록·수정 이력·파일 목록을 포함하고 파일 원본은 포함하지 않습니다. 서버를 종료한 뒤 .data 폴더 전체를 복사하면 계정·기록·첨부 원본까지 백업됩니다.</p></div></section>
 <section className="panel"><SectionHeading title="기록 관리 원칙"/><div className="panel-body"><p>계획과 실제 수행, 관찰과 해석을 분리합니다. AI 초안은 선택한 항목에만 검토 후 반영하고, 이전 기록과 입력 원문을 보존합니다.</p><p>서명한 노트는 잠기며 수정하려면 사유를 남기고 새 리비전을 엽니다. 앱 내 서명은 공인 전자서명이나 규제 준수 인증이 아닙니다.</p><p className="form-hint">동료의 변경은 화면 복귀 시와 15초 간격으로 확인합니다. 동시에 같은 리비전을 수정하면 덮어쓰지 않고 충돌을 안내합니다.</p></div></section>
 </div>{remove&&<Modal title="연구실 접근 해제" onClose={()=>!working&&setRemove(null)}><div className="modal-body"><p>{remove.name} 계정의 이 연구실 접근 권한을 해제합니다. 기존 작성 기록과 이력은 남습니다.</p></div><div className="modal-footer"><Button kind="secondary" disabled={working} onClick={()=>setRemove(null)}>취소</Button><Button kind="danger" disabled={working} onClick={()=>void permission(remove.id,'remove')}>접근 해제</Button></div></Modal>}</>;
}
